<a href="https://colab.research.google.com/github/Arif0000/Pytorch/blob/main/optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 7.1 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [2]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [5]:
import numpy as np

cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df [cols_with_missing_vals].replace(0,np.nan)

df.fillna(df.mean(), inplace=True)
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [15]:
from pandas.core.tools.datetimes import Scalar
X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)

(537, 8)
(231, 8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective(trail):
  n_estimator = trail.suggest_int('n_estimators', 50, 200)
  max_depth = trail.suggest_int('max_depth',3,20)

  model = RandomForestClassifier(n_estimators= n_estimator, max_depth= max_depth, random_state=42)

  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score

In [12]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())

study.optimize(objective, n_trials=50)

[I 2026-03-04 10:23:11,347] A new study created in memory with name: no-name-ef6e8e1e-0add-4e05-a177-5328d144eaba
[I 2026-03-04 10:23:12,448] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 184, 'max_depth': 7}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-03-04 10:23:13,578] Trial 1 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 16}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:15,038] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 11}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:16,426] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 196, 'max_depth': 10}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:17,219] Trial 4 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 140, 'max_depth': 4}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:17,855] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 16}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:18,573] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:19,777] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 7}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:20,279] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:21,423] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 182, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:21,779] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 54, 'max_depth': 14}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:22,518] Trial 11 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 14}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:23,234] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:24,144] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:24,712] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 86, 'max_depth': 12}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:25,530] Trial 15 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:27,089] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 160, 'max_depth': 19}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:28,406] Trial 17 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 128, 'max_depth': 17}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:29,218] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 126, 'max_depth': 13}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:30,244] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 163, 'max_depth': 20}. Best is trial 1 with value: 0.7802607076350093.
[I 2026-03-04 10:23:30,742] Trial 20 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 73, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:31,110] Trial 21 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 55, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:31,661] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 81, 'max_depth': 16}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:32,120] Trial 23 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 71, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:32,576] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:33,191] Trial 25 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 95, 'max_depth': 10}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:33,587] Trial 26 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:34,062] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 69, 'max_depth': 15}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:34,682] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 94, 'max_depth': 13}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:35,009] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 8}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:35,410] Trial 30 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 68, 'max_depth': 4}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:36,159] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:36,850] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 16}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:37,720] Trial 33 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 134, 'max_depth': 20}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:38,286] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:39,767] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 158, 'max_depth': 17}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:41,246] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 147, 'max_depth': 16}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:42,416] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:43,056] Trial 38 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 102, 'max_depth': 11}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:43,844] Trial 39 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:44,347] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:45,086] Trial 41 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:45,940] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 18}. Best is trial 20 with value: 0.7802607076350094.
[I 2026-03-04 10:23:46,719] Trial 43 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:47,425] Trial 44 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 15}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:48,317] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 136, 'max_depth': 16}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:48,907] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 13}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:49,609] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 109, 'max_depth': 14}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:50,250] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 101, 'max_depth': 17}. Best is trial 43 with value: 0.7858472998137803.
[I 2026-03-04 10:23:51,149] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 43 with value: 0.7858472998137803.

In [13]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7858472998137803
Best hyperparameters: {'n_estimators': 121, 'max_depth': 15}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [18]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-03-04 10:26:02,560] A new study created in memory with name: no-name-6e7fff64-f2ae-4e6d-b6c3-b6dbbfce0957
[I 2026-03-04 10:26:03,830] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 87, 'max_depth': 9}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-03-04 10:26:05,103] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 113, 'max_depth': 11}. Best is trial 1 with value: 0.7653631284916201.
[I 2026-03-04 10:26:08,022] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 157, 'max_depth': 18}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-03-04 10:26:08,691] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 52, 'max_depth': 5}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-03-04 10:26:09,648] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 5}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-03-04 10:26:11,355] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 193, 'max_depth': 14}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-03-04 10:26:12,509] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 181, 'max_depth': 15}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-03-04 10:26:12,982] Trial 7 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:13,524] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 83, 'max_depth': 15}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:14,493] Trial 9 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 160, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:15,469] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 157, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:16,427] Trial 11 finished with value: 0.756052141527002 and parameters: {'n_estimators': 173, 'max_depth': 4}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:16,763] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 50, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:17,512] Trial 13 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 138, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:18,672] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 17}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:21,063] Trial 15 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 132, 'max_depth': 4}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:22,336] Trial 16 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 89, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:23,560] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:25,226] Trial 18 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 142, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:26,473] Trial 19 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 106, 'max_depth': 9}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:27,592] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 20}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:28,334] Trial 21 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 121, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:29,283] Trial 22 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 178, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:29,815] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 83, 'max_depth': 15}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:30,352] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 5}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:31,356] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 11}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:32,809] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 198, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:33,359] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 56, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:34,354] Trial 28 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 101, 'max_depth': 17}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:35,241] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:35,672] Trial 30 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 68, 'max_depth': 12}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:36,477] Trial 31 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 148, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:37,191] Trial 32 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:38,106] Trial 33 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 163, 'max_depth': 4}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:38,641] Trial 34 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 89, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:39,028] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:40,131] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 179, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:40,741] Trial 37 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 112, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:41,543] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 129, 'max_depth': 15}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:42,779] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 200, 'max_depth': 11}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:43,212] Trial 40 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 69, 'max_depth': 6}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:43,966] Trial 41 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:44,339] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:44,742] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 64, 'max_depth': 9}. Best is trial 7 with value: 0.7783985102420856.
[I 2026-03-04 10:26:45,649] Trial 44 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 118, 'max_depth': 7}. Best is trial 44 with value: 0.7821229050279329.
[I 2026-03-04 10:26:46,985] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 141, 'max_depth': 14}. Best is trial 44 with value: 0.7821229050279329.
[I 2026-03-04 10:26:47,867] Trial 46 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 89, 'max_depth': 7}. Best is trial 44 with value: 0.7821229050279329.
[I 2026-03-04 10:26:48,649] Trial 47 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 113, 'max_depth': 6}. Best is trial 44 with value: 0.7821229050279329.
[I 2026-03-04 10:26:48,967] Trial 48 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 50, 'max_depth': 7}. Best is trial 44 with value: 0.7821229050279329.
[I 2026-03-04 10:26:50,142] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 190, 'max_depth': 12}. Best is trial 44 with value: 0.7821229050279329.

In [19]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 118, 'max_depth': 7}

In [20]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [21]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [22]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-03-04 10:27:33,236] A new study created in memory with name: no-name-d9b53102-18de-47c6-b765-0eddf40da985
[I 2026-03-04 10:27:34,081] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-04 10:27:36,357] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-04 10:27:37,635] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:39,790] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:42,059] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:42,608] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:43,910] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:44,860] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:45,805] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:47,051] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:48,324] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:50,015] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:51,876] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-04 10:27:52,207] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-04 10:27:52,838] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-04 10:27:53,189] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [23]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [24]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [25]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [26]:
# 1. Optimization History
plot_optimization_history(study).show()

In [27]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [28]:
# 3. Slice Plot
plot_slice(study).show()

In [29]:
# 4. Contour Plot
plot_contour(study).show()

In [30]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [31]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [32]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [33]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-03-04 10:30:47,094] A new study created in memory with name: no-name-47bb60cf-8147-42c7-8a1b-624d0541b6da
[I 2026-03-04 10:30:47,150] Trial 0 finished with value: 0.7765363128491621 and parameters: {'classifier': 'SVM', 'C': 0.14813622362243214, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:47,195] Trial 1 finished with value: 0.74487895716946 and parameters: {'classifier': 'SVM', 'C': 0.5593086566370349, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:47,231] Trial 2 finished with value: 0.6945996275605214 and parameters: {'classifier': 'SVM', 'C': 9.062073128939797, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:51,705] Trial 3 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 226, 'learning_rate': 0.06700305841863906, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:52,805] Trial 4 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 122, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:52,864] Trial 5 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 4.826336243948526, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-03-04 10:30:52,919] Trial 6 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13491422535954664, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:30:56,293] Trial 7 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 127, 'learning_rate': 0.022729853960184055, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:30:56,345] Trial 8 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.3044758800337332, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:30:59,418] Trial 9 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 247, 'learning_rate': 0.04238890586060312, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:30:59,868] Trial 10 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 71, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:30:59,903] Trial 11 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10169628828712983, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:00,295] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 95.80344450669934, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:00,330] Trial 13 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10980593832129337, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:00,368] Trial 14 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.151673069882954, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:01,775] Trial 15 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 279, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:01,813] Trial 16 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 1.1532930935861838, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:01,848] Trial 17 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12440327845860229, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:03,154] Trial 18 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 171, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,399] Trial 19 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 62, 'learning_rate': 0.2883848265066754, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,577] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 17.249695318931597, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,631] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10000051378184849, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,691] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3345685464076621, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,748] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2551892568294245, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,813] Trial 24 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7805261549583735, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,877] Trial 25 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.19997722222036762, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:04,933] Trial 26 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.43347989778082907, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:05,008] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.317354976492045, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:16,020] Trial 28 finished with value: 0.7411545623836125 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 297, 'learning_rate': 0.011323423095970174, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:17,785] Trial 29 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 196, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:17,899] Trial 30 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1817448894634832, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,027] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10448240530100412, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,109] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10393292063063456, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,205] Trial 33 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19710342402861206, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,333] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1556666911685927, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,458] Trial 35 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.31888879921261626, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,543] Trial 36 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.5820810123106828, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:18,706] Trial 37 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10150610399152099, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:26,944] Trial 38 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 125, 'learning_rate': 0.2520741364641933, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:27,370] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 35.330800787015136, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:29,883] Trial 40 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 163, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:29,936] Trial 41 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13662762113653854, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:30,064] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17746771277066267, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:30,229] Trial 43 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1496111120574506, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:30,475] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24660318938765027, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:30,553] Trial 45 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.15487130050940484, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:39,986] Trial 46 finished with value: 0.7262569832402234 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 250, 'learning_rate': 0.10341565959756932, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:40,044] Trial 47 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.46975636172267454, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:40,152] Trial 48 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.14546085584689855, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,282] Trial 49 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 91, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,370] Trial 50 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.36134626069491327, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,418] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13122202328872198, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,480] Trial 52 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23528972220487113, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,530] Trial 53 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14866990960192789, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,586] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1521324017755207, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,641] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14261620856217488, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,708] Trial 56 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.26110780172270803, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:41,786] Trial 57 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.119805164171027, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:44,265] Trial 58 finished with value: 0.7821229050279329 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 208, 'learning_rate': 0.01024662241385895, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:44,356] Trial 59 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.8221529776913061, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:45,803] Trial 60 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 151, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:45,854] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14406503603824297, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:45,936] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13282946258985173, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:45,987] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1967020589499648, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,041] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2933506971403327, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,107] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1337703259311664, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,169] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.219629063834183, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,288] Trial 67 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.45468268261505, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,351] Trial 68 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 1.7990494075059091, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:46,412] Trial 69 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.41160823394957036, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,331] Trial 70 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.16140777599787462, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,381] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12822928881526166, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,429] Trial 72 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16634900376759434, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,481] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12056622251101817, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,531] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1968699008679121, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,587] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.277708743481163, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,649] Trial 76 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 0.10036989837831452, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:48,700] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16692575816322824, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:50,787] Trial 78 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 266, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:50,821] Trial 79 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1402200848496548, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:50,857] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22597291450643953, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.
[I 2026-03-04 10:31:50,890] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1296948177703184, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7895716945996275.

In [34]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)
study.trials_dataframe()

Best trial parameters: {'classifier': 'SVM', 'C': 0.13491422535954664, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [35]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 80
GradientBoosting    10
RandomForest        10
Name: count, dtype: int64

In [36]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.748045
RandomForest        0.764060
SVM                 0.776816
Name: value, dtype: float64

In [37]:
# 1. Optimization History
plot_optimization_history(study).show()

In [38]:
# 3. Slice Plot
plot_slice(study).show()

In [39]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [42]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-03-04 10:34:23,208] A new study created in memory with name: no-name-d5b34ff5-9b4a-49f7-876b-34d5851b66cc

[0]	train-mlogloss:1.06130	eval-mlogloss:1.06428
[1]	train-mlogloss:1.01700	eval-mlogloss:1.01518
[2]	train-mlogloss:0.96786	eval-mlogloss:0.96259
[3]	train-mlogloss:0.92148	eval-mlogloss:0.91514
[4]	train-mlogloss:0.88039	eval-mlogloss:0.87182
[5]	train-mlogloss:0.83912	eval-mlogloss:0.82848
[6]	train-mlogloss:0.80293	eval-mlogloss:0.79047
[7]	train-mlogloss:0.77182	eval-mlogloss:0.76046
[8]	train-mlogloss:0.73947	eval-mlogloss:0.72555
[9]	train-mlogloss:0.70791	eval-mlogloss:0.69225
[10]	train-mlogloss:0.67910	eval-mlogloss:0.66363
[11]	train-mlogloss:0.65196	eval-mlogloss:0.63470
[12]	train-mlogloss:0.63552	eval-mlogloss:0.61840
[13]	train-mlogloss:0.61065	eval-mlogloss:0.59108
[14]	train-mlogloss:0.59557	eval-mlogloss:0.57461
[15]	train-mlogloss:0.57443	eval-mlogloss:0.55257
[16]	train-mlogloss:0.55542	eval-mlogloss:0.53300
[17]	train-mlogloss:0.53946	eval-mlogloss:0.51728
[18]	train-mlogloss:0.52218	eval-mlogloss:0.49962
[19]	train-mlogloss:0.50641	eval-mlogloss:0.48406
[20]	train-mlogloss:0.49173	eval-mlogloss:0.46806
[21]	train-mlogloss:0.47429	eval-mlogloss:0.44893
[22]	train-mlogloss:0.46011	eval-mlogloss:0.43325
[23]	train-mlogloss:0.44353	eval-mlogloss:0.41569
[24]	train-mlogloss:0.42826	eval-mlogloss:0.39893
[25]	train-mlogloss:0.41446	eval-mlogloss:0.38314
[26]	train-mlogloss:0.40376	eval-mlogloss:0.37208
[27]	train-mlogloss:0.39236	eval-mlogloss:0.36006
[28]	train-mlogloss:0.38272	eval-mlogloss:0.35025
[29]	train-mlogloss:0.36983	eval-mlogloss:0.33590
[30]	train-mlogloss:0.35871	eval-mlogloss:0.32316
[31]	train-mlogloss:0.35006	eval-mlogloss:0.31344
[32]	train-mlogloss:0.33964	eval-mlogloss:0.30160
[33]	train-mlogloss:0.33412	eval-mlogloss:0.29541
[34]	train-mlogloss:0.32317	eval-mlogloss:0.28430
[35]	train-mlogloss:0.31405	eval-mlogloss:0.27327
[36]	train-mlogloss:0.30722	eval-mlogloss:0.26584
[37]	train-mlogloss:0.29973	eval-mlogloss:0.25790
[38]	train-mlogloss:0.29318	eval-mlogloss:0.25074
[39]	train-mlogloss:0.28606	eval-mlogloss:0.24377
[40]	train-mlogloss:0.28043	eval-mlogloss:0.23853
[41]	train-mlogloss:0.27327	eval-mlogloss:0.23085
[42]	train-mlogloss:0.26873	eval-mlogloss:0.22509
[43]	train-mlogloss:0.26326	eval-mlogloss:0.21875
[44]	train-mlogloss:0.25812	eval-mlogloss:0.21294
[45]	train-mlogloss:0.25302	eval-mlogloss:0.20814
[46]	train-mlogloss:0.24791	eval-mlogloss:0.20271
[47]	train-mlogloss:0.24348	eval-mlogloss:0.19787
[48]	train-mlogloss:0.23885	eval-mlogloss:0.19306
[49]	train-mlogloss:0.23325	eval-mlogloss:0.18697
[50]	train-mlogloss:0.22779	eval-mlogloss:0.18039
[51]	train-mlogloss:0.22342	eval-mlogloss:0.17598
[52]	train-mlogloss:0.22039	eval-mlogloss:0.17206
[53]	train-mlogloss:0.21620	eval-mlogloss:0.16694
[54]	train-mlogloss:0.21307	eval-mlogloss:0.16362
[55]	train-mlogloss:0.20841	eval-mlogloss:0.15818
[56]	train-mlogloss:0.20508	eval-mlogloss:0.15452
[57]	train-mlogloss:0.20152	eval-mlogloss:0.15019
[58]	train-mlogloss:0.19864	eval-mlogloss:0.14639
[59]	train-mlogloss:0.19564	eval-mlogloss:0.14266
[60]	train-mlogloss:0.19325	eval-mlogloss:0.13993
[61]	train-mlogloss:0.19247	eval-mlogloss:0.13903
[62]	train-mlogloss:0.19049	eval-mlogloss:0.13711
[63]	train-mlogloss:0.19027	eval-mlogloss:0.13649
[64]	train-mlogloss:0.18891	eval-mlogloss:0.13492
[65]	train-mlogloss:0.18640	eval-mlogloss:0.13228
[66]	train-mlogloss:0.18490	eval-mlogloss:0.13062
[67]	train-mlogloss:0.18313	eval-mlogloss:0.12812
[68]	train-mlogloss:0.18191	eval-mlogloss:0.12640
[69]	train-mlogloss:0.18103	eval-mlogloss:0.12537
[70]	train-mlogloss:0.18068	eval-mlogloss:0.12489
[71]	train-mlogloss:0.17898	eval-mlogloss:0.12312
[72]	train-mlogloss:0.17794	eval-mlogloss:0.12144
[73]	train-mlogloss:0.17552	eval-mlogloss:0.11822
[74]	train-mlogloss:0.17343	eval-mlogloss:0.11599
[75]	train-mlogloss:0.17306	eval-mlogloss:0.11559
[76]	train-mlogloss:0.17203	eval-mlogloss:0.11420
[77]	train-mlogloss:0.17115	eval-mlogloss:0.11326
[78]	train-mlogloss:0.17035	eval-mlogloss:0.11212
[79]	train-mlogloss:0.16954	eval-mlogloss:0.11094
[80]	train-mlogloss:0.16902	eval-mlogloss:0.11103
[81]	train-mlogloss:0.16839	eval-mlogloss:0.10991
[82]	train-mlogloss:0.16805	eval-mlogloss:0.11013
[83]	train-mlogloss:0.16795	eval-mlogloss:0.10996
[84]	train-mlogloss:0.16711	eval-mlogloss:0.10890
[85]	train-mlogloss:0.16681	eval-mlogloss:0.10876
[86]	train-mlogloss:0.16693	eval-mlogloss:0.10899
[87]	train-mlogloss:0.16654	eval-mlogloss:0.10862
[88]	train-mlogloss:0.16620	eval-mlogloss:0.10808
[89]	train-mlogloss:0.16545	eval-mlogloss:0.10706
[90]	train-mlogloss:0.16522	eval-mlogloss:0.10706
[91]	train-mlogloss:0.16500	eval-mlogloss:0.10624
[92]	train-mlogloss:0.16427	eval-mlogloss:0.10535
[93]	train-mlogloss:0.16422	eval-mlogloss:0.10487
[94]	train-mlogloss:0.16413	eval-mlogloss:0.10475
[95]	train-mlogloss:0.16392	eval-mlogloss:0.10460
[96]	train-mlogloss:0.16389	eval-mlogloss:0.10457
[97]	train-mlogloss:0.16329	eval-mlogloss:0.10398
[98]	train-mlogloss:0.16326	eval-mlogloss:0.10384
[99]	train-mlogloss:0.16281	eval-mlogloss:0.10396
[100]	train-mlogloss:0.16192	eval-mlogloss:0.10267
[101]	train-mlogloss:0.16062	eval-mlogloss:0.10096
[102]	train-mlogloss:0.16047	eval-mlogloss:0.10072
[103]	train-mlogloss:0.15993	eval-mlogloss:0.09989
[104]	train-mlogloss:0.15992	eval-mlogloss:0.09985
[105]	train-mlogloss:0.15954	eval-mlogloss:0.09935
[106]	train-mlogloss:0.15927	eval-mlogloss:0.09890
[107]	train-mlogloss:0.15928	eval-mlogloss:0.09854
[108]	train-mlogloss:0.15911	eval-mlogloss:0.09844
[109]	train-mlogloss:0.15900	eval-mlogloss:0.09835
[110]	train-mlogloss:0.15847	eval-mlogloss:0.09750
[111]	train-mlogloss:0.15846	eval-mlogloss:0.09747
[112]	train-mlogloss:0.15772	eval-mlogloss:0.09623
[113]	train-mlogloss:0.15715	eval-mlogloss:0.09539
[114]	train-mlogloss:0.15704	eval-mlogloss:0.09491
[115]	train-mlogloss:0.15707	eval-mlogloss:0.09547
[116]	train-mlogloss:0.15707	eval-mlogloss:0.09546
[117]	train-mlogloss:0.15686	eval-mlogloss:0.09506
[118]	train-mlogloss:0.15684	eval-mlogloss:0.09506
[119]	train-mlogloss:0.15672	eval-mlogloss:0.09480
[120]	train-mlogloss:0.15649	eval-mlogloss:0.09441
[121]	train-mlogloss:0.15639	eval-mlogloss:0.09428
[122]	train-mlogloss:0.15561	eval-mlogloss:0.09334
[123]	train-mlogloss:0.15531	eval-mlogloss:0.09284
[124]	train-mlogloss:0.15491	eval-mlogloss:0.09207
[125]	train-mlogloss:0.15486	eval-mlogloss:0.09213
[126]	train-mlogloss:0.15444	eval-mlogloss:0.09228
[127]	train-mlogloss:0.15427	eval-mlogloss:0.09205
[128]	train-mlogloss:0.15420	eval-mlogloss:0.09193
[129]	train-mlogloss:0.15392	eval-mlogloss:0.09181
[130]	train-mlogloss:0.15372	eval-mlogloss:0.09141
[131]	train-mlogloss:0.15380	eval-mlogloss:0.09152
[132]	train-mlogloss:0.15317	eval-mlogloss:0.09079
[133]	train-mlogloss:0.15311	eval-mlogloss:0.09075
[134]	train-mlogloss:0.15311	eval-mlogloss:0.09078
[135]	train-mlogloss:0.15227	eval-mlogloss:0.08974
[136]	train-mlogloss:0.15220	eval-mlogloss:0.08963
[137]	train-mlogloss:0.15217	eval-mlogloss:0.08957
[138]	train-mlogloss:0.15212	eval-mlogloss:0.08956
[139]	train-mlogloss:0.15180	eval-mlogloss:0.08949
[140]	train-mlogloss:0.15179	eval-mlogloss:0.08970
[141]	train-mlogloss:0.15180	eval-mlogloss:0.08968
[142]	train-mlogloss:0.15178	eval-mlogloss:0.08964
[143]	train-mlogloss:0.15170	eval-mlogloss:0.08964
[144]	train-mlogloss:0.15149	eval-mlogloss:0.08933
[145]	train-mlogloss:0.15144	eval-mlogloss:0.08921
[146]	train-mlogloss:0.15137	eval-mlogloss:0.08902
[147]	train-mlogloss:0.15119	eval-mlogloss:0.08875
[148]	train-mlogloss:0.15119	eval-mlogloss:0.08878
[149]	train-mlogloss:0.15123	eval-mlogloss:0.08887
[150]	train-mlogloss:0.15113	eval-mlogloss:0.08867
[151]	train-mlogloss:0.15115	eval-mlogloss:0.08872
[152]	train-mlogloss:0.15115	eval-mlogloss:0.08870
[153]	train-mlogloss:0.15062	eval-mlogloss:0.08818
[154]	train-mlogloss:0.15048	eval-mlogloss:0.08782
[155]	train-mlogloss:0.15032	eval-mlogloss:0.08749
[156]	train-mlogloss:0.15018	eval-mlogloss:0.08727
[157]	train-mlogloss:0.14958	eval-mlogloss:0.08652
[158]	train-mlogloss:0.14954	eval-mlogloss:0.08648
[159]	train-mlogloss:0.14926	eval-mlogloss:0.08633
[160]	train-mlogloss:0.14920	eval-mlogloss:0.08624
[161]	train-mlogloss:0.14915	eval-mlogloss:0.08621
[162]	train-mlogloss:0.14893	eval-mlogloss:0.08608
[163]	train-mlogloss:0.14890	eval-mlogloss:0.08607
[164]	train-mlogloss:0.14888	eval-mlogloss:0.08600
[165]	train-mlogloss:0.14857	eval-mlogloss:0.08556
[166]	train-mlogloss:0.14790	eval-mlogloss:0.08463
[167]	train-mlogloss:0.14790	eval-mlogloss:0.08461
[168]	train-mlogloss:0.14748	eval-mlogloss:0.08489
[169]	train-mlogloss:0.14690	eval-mlogloss:0.08426
[170]	train-mlogloss:0.14683	eval-mlogloss:0.08421
[171]	train-mlogloss:0.14672	eval-mlogloss:0.08430
[172]	train-mlogloss:0.14669	eval-mlogloss:0.08446
[173]	train-mlogloss:0.14669	eval-mlogloss:0.08443
[174]	train-mlogloss:0.14669	eval-mlogloss:0.08432
[175]	train-mlogloss:0.14616	eval-mlogloss:0.08368
[176]	train-mlogloss:0.14622	eval-mlogloss:0.08370
[177]	train-mlogloss:0.14622	eval-mlogloss:0.08382
[178]	train-mlogloss:0.14586	eval-mlogloss:0.08414
[179]	train-mlogloss:0.14586	eval-mlogloss:0.08409
[180]	train-mlogloss:0.14589	eval-mlogloss:0.08371
[181]	train-mlogloss:0.14585	eval-mlogloss:0.08365
[182]	train-mlogloss:0.14589	eval-mlogloss:0.08364
[183]	train-mlogloss:0.14578	eval-mlogloss:0.08352
[184]	train-mlogloss:0.14576	eval-mlogloss:0.08311
[185]	train-mlogloss:0.14580	eval-mlogloss:0.08319
[186]	train-mlogloss:0.14548	eval-mlogloss:0.08336
[187]	train-mlogloss:0.14545	eval-mlogloss:0.08333
[188]	train-mlogloss:0.14538	eval-mlogloss:0.08335
[189]	train-mlogloss:0.14539	eval-mlogloss:0.08354
[190]	train-mlogloss:0.14539	eval-mlogloss:0.08355
[191]	train-mlogloss:0.14540	eval-mlogloss:0.08359
[192]	train-mlogloss:0.14536	eval-mlogloss:0.08359
[193]	train-mlogloss:0.14529	eval-mlogloss:0.08353
[194]	train-mlogloss:0.14524	eval-mlogloss:0.08351
[195]	train-mlogloss:0.14524	eval-mlogloss:0.08351
[196]	train-mlogloss:0.14519	eval-mlogloss:0.08348
[197]	train-mlogloss:0.14516	eval-mlogloss:0.08345
[198]	train-mlogloss:0.14515	eval-mlogloss:0.08327
[199]	train-mlogloss:0.14510	eval-mlogloss:0.08299
[200]	train-mlogloss:0.14501	eval-mlogloss:0.08279
[201]	train-mlogloss:0.14472	eval-mlogloss:0.08203
[202]	train-mlogloss:0.14472	eval-mlogloss:0.08208
[203]	train-mlogloss:0.14463	eval-mlogloss:0.08186
[204]	train-mlogloss:0.14464	eval-mlogloss:0.08213
[205]	train-mlogloss:0.14461	eval-mlogloss:0.08206
[206]	train-mlogloss:0.14449	eval-mlogloss:0.08184
[207]	train-mlogloss:0.14444	eval-mlogloss:0.08169
[208]	train-mlogloss:0.14438	eval-mlogloss:0.08163
[209]	train-mlogloss:0.14431	eval-mlogloss:0.08170
[210]	train-mlogloss:0.14429	eval-mlogloss:0.08176
[211]	train-mlogloss:0.14408	eval-mlogloss:0.08172
[212]	train-mlogloss:0.14393	eval-mlogloss:0.08163
[213]	train-mlogloss:0.14390	eval-mlogloss:0.08140
[214]	train-mlogloss:0.14396	eval-mlogloss:0.08155
[215]	train-mlogloss:0.14394	eval-mlogloss:0.08164
[216]	train-mlogloss:0.14357	eval-mlogloss:0.08106
[217]	train-mlogloss:0.14353	eval-mlogloss:0.08102
[218]	train-mlogloss:0.14353	eval-mlogloss:0.08101
[219]	train-mlogloss:0.14351	eval-mlogloss:0.08104
[220]	train-mlogloss:0.14348	eval-mlogloss:0.08103
[221]	train-mlogloss:0.14343	eval-mlogloss:0.08117
[222]	train-mlogloss:0.14341	eval-mlogloss:0.08105
[223]	train-mlogloss:0.14339	eval-mlogloss:0.08105
[224]	train-mlogloss:0.14336	eval-mlogloss:0.08102
[225]	train-mlogloss:0.14303	eval-mlogloss:0.08068
[226]	train-mlogloss:0.14303	eval-mlogloss:0.08068
[227]	train-mlogloss:0.14301	eval-mlogloss:0.08077
[228]	train-mlogloss:0.14254	eval-mlogloss:0.08003
[229]	train-mlogloss:0.14259	eval-mlogloss:0.08011
[230]	train-mlogloss:0.14261	eval-mlogloss:0.08016
[231]	train-mlogloss:0.14266	eval-mlogloss:0.08018
[232]	train-mlogloss:0.14265	eval-mlogloss:0.08019
[233]	train-mlogloss:0.14262	eval-mlogloss:0.08008
[234]	train-mlogloss:0.14260	eval-mlogloss:0.08009
[235]	train-mlogloss:0.14256	eval-mlogloss:0.08005
[236]	train-mlogloss:0.14250	eval-mlogloss:0.08001
[237]	train-mlogloss:0.14243	eval-mlogloss:0.07983
[238]	train-mlogloss:0.14218	eval-mlogloss:0.07964
[239]	train-mlogloss:0.14211	eval-mlogloss:0.07958
[240]	train-mlogloss:0.14206	eval-mlogloss:0.07897
[241]	train-mlogloss:0.14170	eval-mlogloss:0.07940
[242]	train-mlogloss:0.14172	eval-mlogloss:0.07943
[243]	train-mlogloss:0.14173	eval-mlogloss:0.07958
[244]	train-mlogloss:0.14173	eval-mlogloss:0.07958
[245]	train-mlogloss:0.14168	eval-mlogloss:0.07944
[246]	train-mlogloss:0.14169	eval-mlogloss:0.07958
[247]	train-mlogloss:0.14154	eval-mlogloss:0.07933
[248]	train-mlogloss:0.14154	eval-mlogloss:0.07933
[249]	train-mlogloss:0.14154	eval-mlogloss:0.07931
[250]	train-mlogloss:0.14142	eval-mlogloss:0.07920
[251]	train-mlogloss:0.14142	eval-mlogloss:0.07914
[252]	train-mlogloss:0.14132	eval-mlogloss:0.07889
[253]	train-mlogloss:0.14122	eval-mlogloss:0.07886
[254]	train-mlogloss:0.14124	eval-mlogloss:0.07893
[255]	train-mlogloss:0.14084	eval-mlogloss:0.07906
[256]	train-mlogloss:0.14071	eval-mlogloss:0.07899
[257]	train-mlogloss:0.14076	eval-mlogloss:0.07919
[258]	train-mlogloss:0.14050	eval-mlogloss:0.07887
[259]	train-mlogloss:0.14050	eval-mlogloss:0.07883
[260]	train-mlogloss:0.14049	eval-mlogloss:0.07899
[261]	train-mlogloss:0.14047	eval-mlogloss:0.07872
[262]	train-mlogloss:0.13991	eval-mlogloss:0.07793
[263]	train-mlogloss:0.13990	eval-mlogloss:0.07794
[264]	train-mlogloss:0.13989	eval-mlogloss:0.07792
[265]	train-mlogloss:0.13992	eval-mlogloss:0.07803
[266]	train-mlogloss:0.13991	eval-mlogloss:0.07803
[267]	train-mlogloss:0.13978	eval-mlogloss:0.07787
[268]	train-mlogloss:0.13963	eval-mlogloss:0.07745
[269]	train-mlogloss:0.13953	eval-mlogloss:0.07744
[270]	train-mlogloss:0.13963	eval-mlogloss:0.07743
[271]	train-mlogloss:0.13963	eval-mlogloss:0.07746
[272]	train-mlogloss:0.13963	eval-mlogloss:0.07748
[273]	train-mlogloss:0.13961	eval-mlogloss:0.07747
[274]	train-mlogloss:0.13962	eval-mlogloss:0.07746
[275]	train-mlogloss:0.13944	eval-mlogloss:0.07743
[276]	train-mlogloss:0.13945	eval-mlogloss:0.07747
[277]	train-mlogloss:0.13953	eval-mlogloss:0.07774
[278]	train-mlogloss:0.13954	eval-mlogloss:0.07780
[279]	train-mlogloss:0.13946	eval-mlogloss:0.07773
[280]	train-mlogloss:0.13935	eval-mlogloss:0.07765
[281]	train-mlogloss:0.13939	eval-mlogloss:0.07769
[282]	train-mlogloss:0.13930	eval-mlogloss:0.07741
[283]	train-mlogloss:0.13921	eval-mlogloss:0.07754
[284]	train-mlogloss:0.13920	eval-mlogloss:0.07760
[285]	train-mlogloss:0.13924	eval-mlogloss:0.07764
[286]	train-mlogloss:0.13921	eval-mlogloss:0.07762
[287]	train-mlogloss:0.13902	eval-mlogloss:0.07762
[288]	train-mlogloss:0.13898	eval-mlogloss:0.07760
[289]	train-mlogloss:0.13868	eval-mlogloss:0.07752
[290]	train-mlogloss:0.13856	eval-mlogloss:0.07753
[291]	train-mlogloss:0.13854	eval-mlogloss:0.07716
[292]	train-mlogloss:0.13853	eval-mlogloss:0.07720
[293]	train-mlogloss:0.13825	eval-mlogloss:0.07681
[294]	train-mlogloss:0.13832	eval-mlogloss:0.07696
[295]	train-mlogloss:0.13826	eval-mlogloss:0.07689
[296]	train-mlogloss:0.13825	eval-mlogloss:0.07692
[297]	train-mlogloss:0.13817	eval-mlogloss:0.07677
[298]	train-mlogloss:0.13807	eval-mlogloss:0.07677
[299]	train-mlogloss:0.13803	eval-mlogloss:0.07668

[I 2026-03-04 10:34:25,142] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.0012164703947697255, 'alpha': 0.13314893991574867, 'eta': 0.04235012961350021, 'gamma': 0.0017143784740760264, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.4152043367772039, 'colsample_bytree': 0.5327628311945874}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.93190	eval-mlogloss:0.93770
[1]	train-mlogloss:0.74310	eval-mlogloss:0.73306
[2]	train-mlogloss:0.60437	eval-mlogloss:0.58413
[3]	train-mlogloss:0.49661	eval-mlogloss:0.47255
[4]	train-mlogloss:0.41505	eval-mlogloss:0.38603
[5]	train-mlogloss:0.35060	eval-mlogloss:0.31403
[6]	train-mlogloss:0.30152	eval-mlogloss:0.26301
[7]	train-mlogloss:0.26262	eval-mlogloss:0.22262
[8]	train-mlogloss:0.23414	eval-mlogloss:0.18981
[9]	train-mlogloss:0.21220	eval-mlogloss:0.16452
[10]	train-mlogloss:0.19652	eval-mlogloss:0.14755
[11]	train-mlogloss:0.18979	eval-mlogloss:0.13764
[12]	train-mlogloss:0.18035	eval-mlogloss:0.12754
[13]	train-mlogloss:0.17680	eval-mlogloss:0.12254
[14]	train-mlogloss:0.17583	eval-mlogloss:0.12310
[15]	train-mlogloss:0.17237	eval-mlogloss:0.11768
[16]	train-mlogloss:0.17137	eval-mlogloss:0.11497
[17]	train-mlogloss:0.16708	eval-mlogloss:0.10937
[18]	train-mlogloss:0.16466	eval-mlogloss:0.10618
[19]	train-mlogloss:0.16398	eval-mlogloss:0.10671
[20]	train-mlogloss:0.16379	eval-mlogloss:0.10621
[21]	train-mlogloss:0.16335	eval-mlogloss:0.10627
[22]	train-mlogloss:0.16295	eval-mlogloss:0.10462
[23]	train-mlogloss:0.16045	eval-mlogloss:0.10041
[24]	train-mlogloss:0.15959	eval-mlogloss:0.09991
[25]	train-mlogloss:0.15885	eval-mlogloss:0.09946
[26]	train-mlogloss:0.15814	eval-mlogloss:0.10026
[27]	train-mlogloss:0.15765	eval-mlogloss:0.10001
[28]	train-mlogloss:0.15749	eval-mlogloss:0.10003
[29]	train-mlogloss:0.15744	eval-mlogloss:0.09985
[30]	train-mlogloss:0.15625	eval-mlogloss:0.09801
[31]	train-mlogloss:0.15563	eval-mlogloss:0.09739
[32]	train-mlogloss:0.15512	eval-mlogloss:0.09680
[33]	train-mlogloss:0.15501	eval-mlogloss:0.09544
[34]	train-mlogloss:0.15505	eval-mlogloss:0.09549
[35]	train-mlogloss:0.15477	eval-mlogloss:0.09522
[36]	train-mlogloss:0.15433	eval-mlogloss:0.09484
[37]	train-mlogloss:0.15196	eval-mlogloss:0.09266
[38]	train-mlogloss:0.15206	eval-mlogloss:0.09276
[39]	train-mlogloss:0.15171	eval-mlogloss:0.09218
[40]	train-mlogloss:0.15123	eval-mlogloss:0.09170
[41]	train-mlogloss:0.15078	eval-mlogloss:0.09152
[42]	train-mlogloss:0.15070	eval-mlogloss:0.09033
[43]	train-mlogloss:0.15004	eval-mlogloss:0.08941
[44]	train-mlogloss:0.14995	eval-mlogloss:0.08797
[45]	train-mlogloss:0.14959	eval-mlogloss:0.08771
[46]	train-mlogloss:0.14957	eval-mlogloss:0.08838
[47]	train-mlogloss:0.14956	eval-mlogloss:0.08875
[48]	train-mlogloss:0.14947	eval-mlogloss:0.08855
[49]	train-mlogloss:0.14921	eval-mlogloss:0.08826
[50]	train-mlogloss:0.14909	eval-mlogloss:0.08819
[51]	train-mlogloss:0.14900	eval-mlogloss:0.08817
[52]	train-mlogloss:0.14854	eval-mlogloss:0.08797
[53]	train-mlogloss:0.14853	eval-mlogloss:0.08786
[54]	train-mlogloss:0.14852	eval-mlogloss:0.08758
[55]	train-mlogloss:0.14736	eval-mlogloss:0.08595
[56]	train-mlogloss:0.14732	eval-mlogloss:0.08592
[57]	train-mlogloss:0.14739	eval-mlogloss:0.08557
[58]	train-mlogloss:0.14740	eval-mlogloss:0.08550
[59]	train-mlogloss:0.14697	eval-mlogloss:0.08529
[60]	train-mlogloss:0.14675	eval-mlogloss:0.08530
[61]	train-mlogloss:0.14644	eval-mlogloss:0.08503
[62]	train-mlogloss:0.14635	eval-mlogloss:0.08494
[63]	train-mlogloss:0.14638	eval-mlogloss:0.08334
[64]	train-mlogloss:0.14637	eval-mlogloss:0.08269
[65]	train-mlogloss:0.14641	eval-mlogloss:0.08299
[66]	train-mlogloss:0.14632	eval-mlogloss:0.08303
[67]	train-mlogloss:0.14629	eval-mlogloss:0.08309
[68]	train-mlogloss:0.14600	eval-mlogloss:0.08308
[69]	train-mlogloss:0.14570	eval-mlogloss:0.08247
[70]	train-mlogloss:0.14563	eval-mlogloss:0.08240
[71]	train-mlogloss:0.14560	eval-mlogloss:0.08258
[72]	train-mlogloss:0.14561	eval-mlogloss:0.08285
[73]	train-mlogloss:0.14559	eval-mlogloss:0.08284
[74]	train-mlogloss:0.14560	eval-mlogloss:0.08276
[75]	train-mlogloss:0.14559	eval-mlogloss:0.08337
[76]	train-mlogloss:0.14565	eval-mlogloss:0.08348
[77]	train-mlogloss:0.14547	eval-mlogloss:0.08328
[78]	train-mlogloss:0.14574	eval-mlogloss:0.08368
[79]	train-mlogloss:0.14578	eval-mlogloss:0.08384
[80]	train-mlogloss:0.14569	eval-mlogloss:0.08351
[81]	train-mlogloss:0.14560	eval-mlogloss:0.08238
[82]	train-mlogloss:0.14551	eval-mlogloss:0.08224
[83]	train-mlogloss:0.14546	eval-mlogloss:0.08226
[84]	train-mlogloss:0.14533	eval-mlogloss:0.08200
[85]	train-mlogloss:0.14530	eval-mlogloss:0.08183
[86]	train-mlogloss:0.14533	eval-mlogloss:0.08190
[87]	train-mlogloss:0.14519	eval-mlogloss:0.08180
[88]	train-mlogloss:0.14510	eval-mlogloss:0.08169
[89]	train-mlogloss:0.14458	eval-mlogloss:0.08072
[90]	train-mlogloss:0.14447	eval-mlogloss:0.08070
[91]	train-mlogloss:0.14445	eval-mlogloss:0.08076
[92]	train-mlogloss:0.14411	eval-mlogloss:0.08056
[93]	train-mlogloss:0.14408	eval-mlogloss:0.08036
[94]	train-mlogloss:0.14414	eval-mlogloss:0.08072
[95]	train-mlogloss:0.14435	eval-mlogloss:0.08078
[96]	train-mlogloss:0.14441	eval-mlogloss:0.08054
[97]	train-mlogloss:0.14432	eval-mlogloss:0.08068
[98]	train-mlogloss:0.14455	eval-mlogloss:0.08084
[99]	train-mlogloss:0.14427	eval-mlogloss:0.08057
[100]	train-mlogloss:0.14428	eval-mlogloss:0.08057
[101]	train-mlogloss:0.14412	eval-mlogloss:0.08059
[102]	train-mlogloss:0.14392	eval-mlogloss:0.08048
[103]	train-mlogloss:0.14388	eval-mlogloss:0.08029
[104]	train-mlogloss:0.14390	eval-mlogloss:0.08051
[105]	train-mlogloss:0.14382	eval-mlogloss:0.08035
[106]	train-mlogloss:0.14382	eval-mlogloss:0.08085
[107]	train-mlogloss:0.14393	eval-mlogloss:0.08141
[108]	train-mlogloss:0.14387	eval-mlogloss:0.08140
[109]	train-mlogloss:0.14374	eval-mlogloss:0.08130
[110]	train-mlogloss:0.14382	eval-mlogloss:0.08149
[111]	train-mlogloss:0.14384	eval-mlogloss:0.08160
[112]	train-mlogloss:0.14371	eval-mlogloss:0.08144
[113]	train-mlogloss:0.14379	eval-mlogloss:0.08152
[114]	train-mlogloss:0.14376	eval-mlogloss:0.08035
[115]	train-mlogloss:0.14383	eval-mlogloss:0.08043
[116]	train-mlogloss:0.14382	eval-mlogloss:0.08063
[117]	train-mlogloss:0.14342	eval-mlogloss:0.07987
[118]	train-mlogloss:0.14333	eval-mlogloss:0.08103
[119]	train-mlogloss:0.14314	eval-mlogloss:0.08075
[120]	train-mlogloss:0.14309	eval-mlogloss:0.08081
[121]	train-mlogloss:0.14292	eval-mlogloss:0.08046
[122]	train-mlogloss:0.14287	eval-mlogloss:0.08043
[123]	train-mlogloss:0.14275	eval-mlogloss:0.08045
[124]	train-mlogloss:0.14271	eval-mlogloss:0.07978
[125]	train-mlogloss:0.14264	eval-mlogloss:0.07967
[126]	train-mlogloss:0.14247	eval-mlogloss:0.07947
[127]	train-mlogloss:0.14240	eval-mlogloss:0.07929
[128]	train-mlogloss:0.14243	eval-mlogloss:0.07954
[129]	train-mlogloss:0.14226	eval-mlogloss:0.07947
[130]	train-mlogloss:0.14232	eval-mlogloss:0.07963
[131]	train-mlogloss:0.14236	eval-mlogloss:0.07999
[132]	train-mlogloss:0.14220	eval-mlogloss:0.07933
[133]	train-mlogloss:0.14223	eval-mlogloss:0.07945
[134]	train-mlogloss:0.14227	eval-mlogloss:0.07957
[135]	train-mlogloss:0.14232	eval-mlogloss:0.07981
[136]	train-mlogloss:0.14235	eval-mlogloss:0.07973
[137]	train-mlogloss:0.14202	eval-mlogloss:0.07916
[138]	train-mlogloss:0.14195	eval-mlogloss:0.07892
[139]	train-mlogloss:0.14187	eval-mlogloss:0.07883
[140]	train-mlogloss:0.14187	eval-mlogloss:0.07902
[141]	train-mlogloss:0.14191	eval-mlogloss:0.07916
[142]	train-mlogloss:0.14194	eval-mlogloss:0.07926
[143]	train-mlogloss:0.14187	eval-mlogloss:0.07915
[144]	train-mlogloss:0.14183	eval-mlogloss:0.07926
[145]	train-mlogloss:0.14192	eval-mlogloss:0.07943
[146]	train-mlogloss:0.14175	eval-mlogloss:0.07900
[147]	train-mlogloss:0.14158	eval-mlogloss:0.07824
[148]	train-mlogloss:0.14158	eval-mlogloss:0.07814
[149]	train-mlogloss:0.14162	eval-mlogloss:0.07826
[150]	train-mlogloss:0.14160	eval-mlogloss:0.07788
[151]	train-mlogloss:0.14159	eval-mlogloss:0.07768
[152]	train-mlogloss:0.14151	eval-mlogloss:0.07761
[153]	train-mlogloss:0.14146	eval-mlogloss:0.07773
[154]	train-mlogloss:0.14145	eval-mlogloss:0.07744
[155]	train-mlogloss:0.14158	eval-mlogloss:0.07708
[156]	train-mlogloss:0.14165	eval-mlogloss:0.07695
[157]	train-mlogloss:0.14162	eval-mlogloss:0.07701
[158]	train-mlogloss:0.14157	eval-mlogloss:0.07693
[159]	train-mlogloss:0.14135	eval-mlogloss:0.07691
[160]	train-mlogloss:0.14133	eval-mlogloss:0.07707
[161]	train-mlogloss:0.14124	eval-mlogloss:0.07670
[162]	train-mlogloss:0.14116	eval-mlogloss:0.07670
[163]	train-mlogloss:0.14116	eval-mlogloss:0.07680
[164]	train-mlogloss:0.14122	eval-mlogloss:0.07697
[165]	train-mlogloss:0.14119	eval-mlogloss:0.07706
[166]	train-mlogloss:0.14115	eval-mlogloss:0.07696
[167]	train-mlogloss:0.14114	eval-mlogloss:0.07694
[168]	train-mlogloss:0.14112	eval-mlogloss:0.07688
[169]	train-mlogloss:0.14107	eval-mlogloss:0.07679
[170]	train-mlogloss:0.14104	eval-mlogloss:0.07661
[171]	train-mlogloss:0.14094	eval-mlogloss:0.07664
[172]	train-mlogloss:0.14098	eval-mlogloss:0.07692
[173]	train-mlogloss:0.14097	eval-mlogloss:0.07694
[174]	train-mlogloss:0.14096	eval-mlogloss:0.07741
[175]	train-mlogloss:0.14093	eval-mlogloss:0.07730
[176]	train-mlogloss:0.14097	eval-mlogloss:0.07686
[177]	train-mlogloss:0.14100	eval-mlogloss:0.07668
[178]	train-mlogloss:0.14094	eval-mlogloss:0.07669
[179]	train-mlogloss:0.14092	eval-mlogloss:0.07662
[180]	train-mlogloss:0.14097	eval-mlogloss:0.07553
[181]	train-mlogloss:0.14091	eval-mlogloss:0.07555
[182]	train-mlogloss:0.14096	eval-mlogloss:0.07526
[183]	train-mlogloss:0.14089	eval-mlogloss:0.07548
[184]	train-mlogloss:0.14089	eval-mlogloss:0.07543
[185]	train-mlogloss:0.14087	eval-mlogloss:0.07555
[186]	train-mlogloss:0.14079	eval-mlogloss:0.07551
[187]	train-mlogloss:0.14079	eval-mlogloss:0.07553
[188]	train-mlogloss:0.14077	eval-mlogloss:0.07567
[189]	train-mlogloss:0.14077	eval-mlogloss:0.07572
[190]	train-mlogloss:0.14075	eval-mlogloss:0.07580
[191]	train-mlogloss:0.14070	eval-mlogloss:0.07595
[192]	train-mlogloss:0.14071	eval-mlogloss:0.07583
[193]	train-mlogloss:0.14067	eval-mlogloss:0.07567
[194]	train-mlogloss:0.14058	eval-mlogloss:0.07579
[195]	train-mlogloss:0.14056	eval-mlogloss:0.07578
[196]	train-mlogloss:0.14047	eval-mlogloss:0.07588
[197]	train-mlogloss:0.14047	eval-mlogloss:0.07560
[198]	train-mlogloss:0.14054	eval-mlogloss:0.07552
[199]	train-mlogloss:0.14057	eval-mlogloss:0.07556
[200]	train-mlogloss:0.14052	eval-mlogloss:0.07551
[201]	train-mlogloss:0.14071	eval-mlogloss:0.07531
[202]	train-mlogloss:0.14070	eval-mlogloss:0.07538
[203]	train-mlogloss:0.14060	eval-mlogloss:0.07558
[204]	train-mlogloss:0.14057	eval-mlogloss:0.07644
[205]	train-mlogloss:0.14043	eval-mlogloss:0.07634
[206]	train-mlogloss:0.14041	eval-mlogloss:0.07641
[207]	train-mlogloss:0.14042	eval-mlogloss:0.07637
[208]	train-mlogloss:0.14039	eval-mlogloss:0.07657
[209]	train-mlogloss:0.14041	eval-mlogloss:0.07643
[210]	train-mlogloss:0.14043	eval-mlogloss:0.07558
[211]	train-mlogloss:0.14042	eval-mlogloss:0.07554
[212]	train-mlogloss:0.14021	eval-mlogloss:0.07542

[I 2026-03-04 10:34:27,883] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.053404790073419806, 'alpha': 4.565446228428123e-07, 'eta': 0.2006477021425775, 'gamma': 3.369866396516876e-08, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7833412371547624, 'colsample_bytree': 0.685383302408495}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.99693	eval-mlogloss:0.99010
[1]	train-mlogloss:0.90840	eval-mlogloss:0.89650
[2]	train-mlogloss:0.83100	eval-mlogloss:0.81333
[3]	train-mlogloss:0.76027	eval-mlogloss:0.73919
[4]	train-mlogloss:0.70066	eval-mlogloss:0.67496
[5]	train-mlogloss:0.64553	eval-mlogloss:0.61527
[6]	train-mlogloss:0.59750	eval-mlogloss:0.56436
[7]	train-mlogloss:0.55443	eval-mlogloss:0.51858
[8]	train-mlogloss:0.51529	eval-mlogloss:0.47691
[9]	train-mlogloss:0.47947	eval-mlogloss:0.43801
[10]	train-mlogloss:0.44725	eval-mlogloss:0.40349
[11]	train-mlogloss:0.41724	eval-mlogloss:0.37205
[12]	train-mlogloss:0.39325	eval-mlogloss:0.34653
[13]	train-mlogloss:0.37104	eval-mlogloss:0.32151
[14]	train-mlogloss:0.35031	eval-mlogloss:0.29990
[15]	train-mlogloss:0.33210	eval-mlogloss:0.28008
[16]	train-mlogloss:0.31781	eval-mlogloss:0.26403
[17]	train-mlogloss:0.30451	eval-mlogloss:0.24933
[18]	train-mlogloss:0.29231	eval-mlogloss:0.23686
[19]	train-mlogloss:0.28142	eval-mlogloss:0.22463
[20]	train-mlogloss:0.27107	eval-mlogloss:0.21304
[21]	train-mlogloss:0.26185	eval-mlogloss:0.20165
[22]	train-mlogloss:0.25338	eval-mlogloss:0.19222
[23]	train-mlogloss:0.24524	eval-mlogloss:0.18354
[24]	train-mlogloss:0.24191	eval-mlogloss:0.17915
[25]	train-mlogloss:0.23435	eval-mlogloss:0.17139
[26]	train-mlogloss:0.23159	eval-mlogloss:0.16715
[27]	train-mlogloss:0.23028	eval-mlogloss:0.16546
[28]	train-mlogloss:0.22765	eval-mlogloss:0.16214
[29]	train-mlogloss:0.22625	eval-mlogloss:0.16020
[30]	train-mlogloss:0.22332	eval-mlogloss:0.15711
[31]	train-mlogloss:0.22108	eval-mlogloss:0.15434
[32]	train-mlogloss:0.21921	eval-mlogloss:0.15204
[33]	train-mlogloss:0.21901	eval-mlogloss:0.15112
[34]	train-mlogloss:0.21875	eval-mlogloss:0.15080
[35]	train-mlogloss:0.21858	eval-mlogloss:0.15070
[36]	train-mlogloss:0.21837	eval-mlogloss:0.15064
[37]	train-mlogloss:0.21595	eval-mlogloss:0.14723
[38]	train-mlogloss:0.21589	eval-mlogloss:0.14693
[39]	train-mlogloss:0.21532	eval-mlogloss:0.14623
[40]	train-mlogloss:0.21515	eval-mlogloss:0.14608
[41]	train-mlogloss:0.21256	eval-mlogloss:0.14271
[42]	train-mlogloss:0.21238	eval-mlogloss:0.14188
[43]	train-mlogloss:0.21178	eval-mlogloss:0.14112
[44]	train-mlogloss:0.21159	eval-mlogloss:0.14022
[45]	train-mlogloss:0.21132	eval-mlogloss:0.14002
[46]	train-mlogloss:0.21118	eval-mlogloss:0.13974
[47]	train-mlogloss:0.21091	eval-mlogloss:0.13939
[48]	train-mlogloss:0.21087	eval-mlogloss:0.13913
[49]	train-mlogloss:0.21075	eval-mlogloss:0.13904
[50]	train-mlogloss:0.20941	eval-mlogloss:0.13728
[51]	train-mlogloss:0.20931	eval-mlogloss:0.13708
[52]	train-mlogloss:0.20913	eval-mlogloss:0.13707
[53]	train-mlogloss:0.20909	eval-mlogloss:0.13687
[54]	train-mlogloss:0.20900	eval-mlogloss:0.13670
[55]	train-mlogloss:0.20769	eval-mlogloss:0.13516
[56]	train-mlogloss:0.20761	eval-mlogloss:0.13510
[57]	train-mlogloss:0.20754	eval-mlogloss:0.13459
[58]	train-mlogloss:0.20752	eval-mlogloss:0.13453
[59]	train-mlogloss:0.20720	eval-mlogloss:0.13426
[60]	train-mlogloss:0.20716	eval-mlogloss:0.13430
[61]	train-mlogloss:0.20697	eval-mlogloss:0.13416
[62]	train-mlogloss:0.20684	eval-mlogloss:0.13411
[63]	train-mlogloss:0.20675	eval-mlogloss:0.13335
[64]	train-mlogloss:0.20665	eval-mlogloss:0.13315
[65]	train-mlogloss:0.20665	eval-mlogloss:0.13315
[66]	train-mlogloss:0.20656	eval-mlogloss:0.13327
[67]	train-mlogloss:0.20654	eval-mlogloss:0.13328
[68]	train-mlogloss:0.20631	eval-mlogloss:0.13322
[69]	train-mlogloss:0.20622	eval-mlogloss:0.13306
[70]	train-mlogloss:0.20604	eval-mlogloss:0.13302
[71]	train-mlogloss:0.20597	eval-mlogloss:0.13264
[72]	train-mlogloss:0.20589	eval-mlogloss:0.13257
[73]	train-mlogloss:0.20585	eval-mlogloss:0.13242
[74]	train-mlogloss:0.20575	eval-mlogloss:0.13256
[75]	train-mlogloss:0.20554	eval-mlogloss:0.13255
[76]	train-mlogloss:0.20548	eval-mlogloss:0.13269
[77]	train-mlogloss:0.20537	eval-mlogloss:0.13261
[78]	train-mlogloss:0.20524	eval-mlogloss:0.13273
[79]	train-mlogloss:0.20513	eval-mlogloss:0.13276
[80]	train-mlogloss:0.20503	eval-mlogloss:0.13289
[81]	train-mlogloss:0.20493	eval-mlogloss:0.13237
[82]	train-mlogloss:0.20494	eval-mlogloss:0.13240
[83]	train-mlogloss:0.20481	eval-mlogloss:0.13231
[84]	train-mlogloss:0.20465	eval-mlogloss:0.13227
[85]	train-mlogloss:0.20453	eval-mlogloss:0.13221
[86]	train-mlogloss:0.20444	eval-mlogloss:0.13220
[87]	train-mlogloss:0.20432	eval-mlogloss:0.13221
[88]	train-mlogloss:0.20423	eval-mlogloss:0.13218
[89]	train-mlogloss:0.20230	eval-mlogloss:0.12958
[90]	train-mlogloss:0.20225	eval-mlogloss:0.12964
[91]	train-mlogloss:0.20226	eval-mlogloss:0.12966
[92]	train-mlogloss:0.20204	eval-mlogloss:0.12943
[93]	train-mlogloss:0.20200	eval-mlogloss:0.12933
[94]	train-mlogloss:0.20204	eval-mlogloss:0.12939
[95]	train-mlogloss:0.20199	eval-mlogloss:0.12946
[96]	train-mlogloss:0.20192	eval-mlogloss:0.12951
[97]	train-mlogloss:0.20184	eval-mlogloss:0.12946
[98]	train-mlogloss:0.20191	eval-mlogloss:0.12951
[99]	train-mlogloss:0.20172	eval-mlogloss:0.12928
[100]	train-mlogloss:0.20159	eval-mlogloss:0.12931
[101]	train-mlogloss:0.20147	eval-mlogloss:0.12925
[102]	train-mlogloss:0.20141	eval-mlogloss:0.12928
[103]	train-mlogloss:0.20136	eval-mlogloss:0.12917
[104]	train-mlogloss:0.20137	eval-mlogloss:0.12921
[105]	train-mlogloss:0.20131	eval-mlogloss:0.12905
[106]	train-mlogloss:0.20108	eval-mlogloss:0.12876
[107]	train-mlogloss:0.20098	eval-mlogloss:0.12884
[108]	train-mlogloss:0.20094	eval-mlogloss:0.12869
[109]	train-mlogloss:0.20085	eval-mlogloss:0.12855
[110]	train-mlogloss:0.20081	eval-mlogloss:0.12864
[111]	train-mlogloss:0.20075	eval-mlogloss:0.12871
[112]	train-mlogloss:0.20074	eval-mlogloss:0.12870
[113]	train-mlogloss:0.20076	eval-mlogloss:0.12873
[114]	train-mlogloss:0.20071	eval-mlogloss:0.12878
[115]	train-mlogloss:0.20074	eval-mlogloss:0.12883
[116]	train-mlogloss:0.20061	eval-mlogloss:0.12881
[117]	train-mlogloss:0.20051	eval-mlogloss:0.12885
[118]	train-mlogloss:0.20049	eval-mlogloss:0.12887
[119]	train-mlogloss:0.20039	eval-mlogloss:0.12881
[120]	train-mlogloss:0.20039	eval-mlogloss:0.12885
[121]	train-mlogloss:0.20036	eval-mlogloss:0.12884
[122]	train-mlogloss:0.20031	eval-mlogloss:0.12883
[123]	train-mlogloss:0.20029	eval-mlogloss:0.12882
[124]	train-mlogloss:0.19946	eval-mlogloss:0.12754
[125]	train-mlogloss:0.19940	eval-mlogloss:0.12760
[126]	train-mlogloss:0.19937	eval-mlogloss:0.12739
[127]	train-mlogloss:0.19932	eval-mlogloss:0.12741
[128]	train-mlogloss:0.19930	eval-mlogloss:0.12723
[129]	train-mlogloss:0.19915	eval-mlogloss:0.12719
[130]	train-mlogloss:0.19911	eval-mlogloss:0.12715
[131]	train-mlogloss:0.19911	eval-mlogloss:0.12716
[132]	train-mlogloss:0.19902	eval-mlogloss:0.12693
[133]	train-mlogloss:0.19902	eval-mlogloss:0.12693
[134]	train-mlogloss:0.19902	eval-mlogloss:0.12693
[135]	train-mlogloss:0.19894	eval-mlogloss:0.12688
[136]	train-mlogloss:0.19895	eval-mlogloss:0.12690
[137]	train-mlogloss:0.19874	eval-mlogloss:0.12671
[138]	train-mlogloss:0.19869	eval-mlogloss:0.12660
[139]	train-mlogloss:0.19861	eval-mlogloss:0.12658
[140]	train-mlogloss:0.19858	eval-mlogloss:0.12651
[141]	train-mlogloss:0.19858	eval-mlogloss:0.12634
[142]	train-mlogloss:0.19861	eval-mlogloss:0.12640
[143]	train-mlogloss:0.19854	eval-mlogloss:0.12642
[144]	train-mlogloss:0.19852	eval-mlogloss:0.12638
[145]	train-mlogloss:0.19849	eval-mlogloss:0.12644
[146]	train-mlogloss:0.19831	eval-mlogloss:0.12627
[147]	train-mlogloss:0.19819	eval-mlogloss:0.12625
[148]	train-mlogloss:0.19822	eval-mlogloss:0.12631
[149]	train-mlogloss:0.19825	eval-mlogloss:0.12639
[150]	train-mlogloss:0.19816	eval-mlogloss:0.12638
[151]	train-mlogloss:0.19814	eval-mlogloss:0.12629
[152]	train-mlogloss:0.19816	eval-mlogloss:0.12633
[153]	train-mlogloss:0.19810	eval-mlogloss:0.12640
[154]	train-mlogloss:0.19809	eval-mlogloss:0.12627
[155]	train-mlogloss:0.19804	eval-mlogloss:0.12632
[156]	train-mlogloss:0.19806	eval-mlogloss:0.12625
[157]	train-mlogloss:0.19805	eval-mlogloss:0.12623
[158]	train-mlogloss:0.19801	eval-mlogloss:0.12616
[159]	train-mlogloss:0.19787	eval-mlogloss:0.12616
[160]	train-mlogloss:0.19771	eval-mlogloss:0.12613
[161]	train-mlogloss:0.19758	eval-mlogloss:0.12601
[162]	train-mlogloss:0.19750	eval-mlogloss:0.12600
[163]	train-mlogloss:0.19751	eval-mlogloss:0.12605
[164]	train-mlogloss:0.19752	eval-mlogloss:0.12608
[165]	train-mlogloss:0.19743	eval-mlogloss:0.12603
[166]	train-mlogloss:0.19740	eval-mlogloss:0.12596
[167]	train-mlogloss:0.19740	eval-mlogloss:0.12597
[168]	train-mlogloss:0.19740	eval-mlogloss:0.12596
[169]	train-mlogloss:0.19733	eval-mlogloss:0.12590
[170]	train-mlogloss:0.19728	eval-mlogloss:0.12568
[171]	train-mlogloss:0.19722	eval-mlogloss:0.12568
[172]	train-mlogloss:0.19722	eval-mlogloss:0.12558
[173]	train-mlogloss:0.19712	eval-mlogloss:0.12555
[174]	train-mlogloss:0.19714	eval-mlogloss:0.12569
[175]	train-mlogloss:0.19711	eval-mlogloss:0.12565
[176]	train-mlogloss:0.19704	eval-mlogloss:0.12569
[177]	train-mlogloss:0.19702	eval-mlogloss:0.12555
[178]	train-mlogloss:0.19696	eval-mlogloss:0.12547
[179]	train-mlogloss:0.19697	eval-mlogloss:0.12543
[180]	train-mlogloss:0.19693	eval-mlogloss:0.12490
[181]	train-mlogloss:0.19689	eval-mlogloss:0.12497
[182]	train-mlogloss:0.19693	eval-mlogloss:0.12484
[183]	train-mlogloss:0.19692	eval-mlogloss:0.12491
[184]	train-mlogloss:0.19689	eval-mlogloss:0.12494
[185]	train-mlogloss:0.19688	eval-mlogloss:0.12501
[186]	train-mlogloss:0.19685	eval-mlogloss:0.12460
[187]	train-mlogloss:0.19685	eval-mlogloss:0.12465
[188]	train-mlogloss:0.19679	eval-mlogloss:0.12469
[189]	train-mlogloss:0.19679	eval-mlogloss:0.12471
[190]	train-mlogloss:0.19676	eval-mlogloss:0.12486
[191]	train-mlogloss:0.19676	eval-mlogloss:0.12482
[192]	train-mlogloss:0.19676	eval-mlogloss:0.12482
[193]	train-mlogloss:0.19676	eval-mlogloss:0.12475
[194]	train-mlogloss:0.19676	eval-mlogloss:0.12479
[195]	train-mlogloss:0.19677	eval-mlogloss:0.12475
[196]	train-mlogloss:0.19667	eval-mlogloss:0.12478
[197]	train-mlogloss:0.19668	eval-mlogloss:0.12471
[198]	train-mlogloss:0.19669	eval-mlogloss:0.12463
[199]	train-mlogloss:0.19667	eval-mlogloss:0.12466
[200]	train-mlogloss:0.19667	eval-mlogloss:0.12467
[201]	train-mlogloss:0.19670	eval-mlogloss:0.12458
[202]	train-mlogloss:0.19671	eval-mlogloss:0.12456
[203]	train-mlogloss:0.19668	eval-mlogloss:0.12458
[204]	train-mlogloss:0.19670	eval-mlogloss:0.12481
[205]	train-mlogloss:0.19670	eval-mlogloss:0.12459
[206]	train-mlogloss:0.19668	eval-mlogloss:0.12464
[207]	train-mlogloss:0.19666	eval-mlogloss:0.12460
[208]	train-mlogloss:0.19660	eval-mlogloss:0.12463
[209]	train-mlogloss:0.19661	eval-mlogloss:0.12466
[210]	train-mlogloss:0.19657	eval-mlogloss:0.12423
[211]	train-mlogloss:0.19658	eval-mlogloss:0.12424
[212]	train-mlogloss:0.19646	eval-mlogloss:0.12414
[213]	train-mlogloss:0.19647	eval-mlogloss:0.12417
[214]	train-mlogloss:0.19646	eval-mlogloss:0.12421
[215]	train-mlogloss:0.19644	eval-mlogloss:0.12424
[216]	train-mlogloss:0.19645	eval-mlogloss:0.12426
[217]	train-mlogloss:0.19644	eval-mlogloss:0.12420
[218]	train-mlogloss:0.19644	eval-mlogloss:0.12424
[219]	train-mlogloss:0.19645	eval-mlogloss:0.12416
[220]	train-mlogloss:0.19645	eval-mlogloss:0.12405
[221]	train-mlogloss:0.19644	eval-mlogloss:0.12408
[222]	train-mlogloss:0.19641	eval-mlogloss:0.12408
[223]	train-mlogloss:0.19638	eval-mlogloss:0.12407
[224]	train-mlogloss:0.19635	eval-mlogloss:0.12367
[225]	train-mlogloss:0.19638	eval-mlogloss:0.12365
[226]	train-mlogloss:0.19638	eval-mlogloss:0.12362
[227]	train-mlogloss:0.19636	eval-mlogloss:0.12365
[228]	train-mlogloss:0.19633	eval-mlogloss:0.12360
[229]	train-mlogloss:0.19631	eval-mlogloss:0.12370
[230]	train-mlogloss:0.19627	eval-mlogloss:0.12363
[231]	train-mlogloss:0.19625	eval-mlogloss:0.12363
[232]	train-mlogloss:0.19625	eval-mlogloss:0.12365
[233]	train-mlogloss:0.19625	eval-mlogloss:0.12366
[234]	train-mlogloss:0.19626	eval-mlogloss:0.12383
[235]	train-mlogloss:0.19625	eval-mlogloss:0.12378
[236]	train-mlogloss:0.19621	eval-mlogloss:0.12386
[237]	train-mlogloss:0.19621	eval-mlogloss:0.12387
[238]	train-mlogloss:0.19614	eval-mlogloss:0.12382
[239]	train-mlogloss:0.19614	eval-mlogloss:0.12383
[240]	train-mlogloss:0.19615	eval-mlogloss:0.12392
[241]	train-mlogloss:0.19612	eval-mlogloss:0.12395
[242]	train-mlogloss:0.19613	eval-mlogloss:0.12401
[243]	train-mlogloss:0.19612	eval-mlogloss:0.12397
[244]	train-mlogloss:0.19612	eval-mlogloss:0.12399
[245]	train-mlogloss:0.19611	eval-mlogloss:0.12392
[246]	train-mlogloss:0.19610	eval-mlogloss:0.12377
[247]	train-mlogloss:0.19610	eval-mlogloss:0.12380
[248]	train-mlogloss:0.19610	eval-mlogloss:0.12379
[249]	train-mlogloss:0.19612	eval-mlogloss:0.12376
[250]	train-mlogloss:0.19613	eval-mlogloss:0.12366
[251]	train-mlogloss:0.19614	eval-mlogloss:0.12368
[252]	train-mlogloss:0.19616	eval-mlogloss:0.12356
[253]	train-mlogloss:0.19618	eval-mlogloss:0.12355
[254]	train-mlogloss:0.19609	eval-mlogloss:0.12356
[255]	train-mlogloss:0.19603	eval-mlogloss:0.12354
[256]	train-mlogloss:0.19602	eval-mlogloss:0.12356
[257]	train-mlogloss:0.19604	eval-mlogloss:0.12354
[258]	train-mlogloss:0.19603	eval-mlogloss:0.12354
[259]	train-mlogloss:0.19602	eval-mlogloss:0.12355
[260]	train-mlogloss:0.19602	eval-mlogloss:0.12354
[261]	train-mlogloss:0.19602	eval-mlogloss:0.12363
[262]	train-mlogloss:0.19601	eval-mlogloss:0.12364
[263]	train-mlogloss:0.19598	eval-mlogloss:0.12360
[264]	train-mlogloss:0.19597	eval-mlogloss:0.12359
[265]	train-mlogloss:0.19599	eval-mlogloss:0.12359
[266]	train-mlogloss:0.19599	eval-mlogloss:0.12365
[267]	train-mlogloss:0.19604	eval-mlogloss:0.12356
[268]	train-mlogloss:0.19593	eval-mlogloss:0.12348
[269]	train-mlogloss:0.19577	eval-mlogloss:0.12341
[270]	train-mlogloss:0.19577	eval-mlogloss:0.12340
[271]	train-mlogloss:0.19577	eval-mlogloss:0.12341
[272]	train-mlogloss:0.19574	eval-mlogloss:0.12344
[273]	train-mlogloss:0.19569	eval-mlogloss:0.12334
[274]	train-mlogloss:0.19569	eval-mlogloss:0.12329
[275]	train-mlogloss:0.19564	eval-mlogloss:0.12332
[276]	train-mlogloss:0.19564	eval-mlogloss:0.12333
[277]	train-mlogloss:0.19560	eval-mlogloss:0.12332
[278]	train-mlogloss:0.19547	eval-mlogloss:0.12318
[279]	train-mlogloss:0.19547	eval-mlogloss:0.12320
[280]	train-mlogloss:0.19548	eval-mlogloss:0.12310
[281]	train-mlogloss:0.19548	eval-mlogloss:0.12314
[282]	train-mlogloss:0.19548	eval-mlogloss:0.12298
[283]	train-mlogloss:0.19547	eval-mlogloss:0.12284
[284]	train-mlogloss:0.19547	eval-mlogloss:0.12289
[285]	train-mlogloss:0.19548	eval-mlogloss:0.12283
[286]	train-mlogloss:0.19544	eval-mlogloss:0.12293
[287]	train-mlogloss:0.19544	eval-mlogloss:0.12289
[288]	train-mlogloss:0.19544	eval-mlogloss:0.12290
[289]	train-mlogloss:0.19543	eval-mlogloss:0.12290
[290]	train-mlogloss:0.19542	eval-mlogloss:0.12285
[291]	train-mlogloss:0.19541	eval-mlogloss:0.12295
[292]	train-mlogloss:0.19546	eval-mlogloss:0.12296
[293]	train-mlogloss:0.19546	eval-mlogloss:0.12302
[294]	train-mlogloss:0.19545	eval-mlogloss:0.12295
[295]	train-mlogloss:0.19542	eval-mlogloss:0.12284
[296]	train-mlogloss:0.19543	eval-mlogloss:0.12295
[297]	train-mlogloss:0.19546	eval-mlogloss:0.12309
[298]	train-mlogloss:0.19545	eval-mlogloss:0.12288
[299]	train-mlogloss:0.19544	eval-mlogloss:0.12281

[I 2026-03-04 10:34:32,338] Trial 2 finished with value: 1.0 and parameters: {'lambda': 0.004326560810323187, 'alpha': 2.4701017121609434e-05, 'eta': 0.08070868318974914, 'gamma': 0.006394469858801021, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.7428964420919795, 'colsample_bytree': 0.9554931457920353}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.91333	eval-mlogloss:0.90465
[1]	train-mlogloss:0.71656	eval-mlogloss:0.69381

[I 2026-03-04 10:34:32,386] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.79703	eval-mlogloss:0.77739
[1]	train-mlogloss:0.64872	eval-mlogloss:0.60569

[I 2026-03-04 10:34:32,423] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08362	eval-mlogloss:1.08707
[1]	train-mlogloss:1.04920	eval-mlogloss:1.05105
[2]	train-mlogloss:1.01586	eval-mlogloss:1.01548
[3]	train-mlogloss:0.99139	eval-mlogloss:0.98851
[4]	train-mlogloss:0.96573	eval-mlogloss:0.96194
[5]	train-mlogloss:0.93624	eval-mlogloss:0.93056
[6]	train-mlogloss:0.91446	eval-mlogloss:0.90891
[7]	train-mlogloss:0.89798	eval-mlogloss:0.89342
[8]	train-mlogloss:0.87156	eval-mlogloss:0.86570
[9]	train-mlogloss:0.85201	eval-mlogloss:0.84579
[10]	train-mlogloss:0.82734	eval-mlogloss:0.82054
[11]	train-mlogloss:0.80588	eval-mlogloss:0.79827
[12]	train-mlogloss:0.79705	eval-mlogloss:0.78870
[13]	train-mlogloss:0.77497	eval-mlogloss:0.76441
[14]	train-mlogloss:0.76742	eval-mlogloss:0.75801
[15]	train-mlogloss:0.75437	eval-mlogloss:0.74583
[16]	train-mlogloss:0.74083	eval-mlogloss:0.73147
[17]	train-mlogloss:0.72510	eval-mlogloss:0.71665
[18]	train-mlogloss:0.71331	eval-mlogloss:0.70537
[19]	train-mlogloss:0.70186	eval-mlogloss:0.69491
[20]	train-mlogloss:0.68330	eval-mlogloss:0.67488
[21]	train-mlogloss:0.67042	eval-mlogloss:0.66141
[22]	train-mlogloss:0.65935	eval-mlogloss:0.64973
[23]	train-mlogloss:0.64199	eval-mlogloss:0.63112
[24]	train-mlogloss:0.63227	eval-mlogloss:0.62088
[25]	train-mlogloss:0.62024	eval-mlogloss:0.60742
[26]	train-mlogloss:0.60718	eval-mlogloss:0.59436
[27]	train-mlogloss:0.60306	eval-mlogloss:0.59138
[28]	train-mlogloss:0.59781	eval-mlogloss:0.58756
[29]	train-mlogloss:0.58565	eval-mlogloss:0.57393
[30]	train-mlogloss:0.57485	eval-mlogloss:0.56289
[31]	train-mlogloss:0.57137	eval-mlogloss:0.56033
[32]	train-mlogloss:0.56390	eval-mlogloss:0.55348
[33]	train-mlogloss:0.55748	eval-mlogloss:0.54687
[34]	train-mlogloss:0.54564	eval-mlogloss:0.53433
[35]	train-mlogloss:0.53870	eval-mlogloss:0.52657
[36]	train-mlogloss:0.53315	eval-mlogloss:0.52188
[37]	train-mlogloss:0.52406	eval-mlogloss:0.51298
[38]	train-mlogloss:0.51424	eval-mlogloss:0.50237
[39]	train-mlogloss:0.50686	eval-mlogloss:0.49574
[40]	train-mlogloss:0.50310	eval-mlogloss:0.49274
[41]	train-mlogloss:0.49466	eval-mlogloss:0.48309
[42]	train-mlogloss:0.49207	eval-mlogloss:0.48108
[43]	train-mlogloss:0.48394	eval-mlogloss:0.47274
[44]	train-mlogloss:0.47563	eval-mlogloss:0.46364
[45]	train-mlogloss:0.47117	eval-mlogloss:0.45866
[46]	train-mlogloss:0.46335	eval-mlogloss:0.45061
[47]	train-mlogloss:0.45796	eval-mlogloss:0.44549
[48]	train-mlogloss:0.45003	eval-mlogloss:0.43748
[49]	train-mlogloss:0.44189	eval-mlogloss:0.42940
[50]	train-mlogloss:0.43394	eval-mlogloss:0.42031
[51]	train-mlogloss:0.42928	eval-mlogloss:0.41550
[52]	train-mlogloss:0.42474	eval-mlogloss:0.41166
[53]	train-mlogloss:0.41554	eval-mlogloss:0.40107
[54]	train-mlogloss:0.41103	eval-mlogloss:0.39623
[55]	train-mlogloss:0.40188	eval-mlogloss:0.38646
[56]	train-mlogloss:0.39496	eval-mlogloss:0.37924
[57]	train-mlogloss:0.38652	eval-mlogloss:0.36948
[58]	train-mlogloss:0.38230	eval-mlogloss:0.36561
[59]	train-mlogloss:0.37977	eval-mlogloss:0.36329
[60]	train-mlogloss:0.37417	eval-mlogloss:0.35701
[61]	train-mlogloss:0.36949	eval-mlogloss:0.35214
[62]	train-mlogloss:0.36170	eval-mlogloss:0.34397
[63]	train-mlogloss:0.35803	eval-mlogloss:0.33999
[64]	train-mlogloss:0.35586	eval-mlogloss:0.33794
[65]	train-mlogloss:0.35212	eval-mlogloss:0.33448
[66]	train-mlogloss:0.34632	eval-mlogloss:0.32824
[67]	train-mlogloss:0.34214	eval-mlogloss:0.32408
[68]	train-mlogloss:0.34040	eval-mlogloss:0.32249
[69]	train-mlogloss:0.33371	eval-mlogloss:0.31505
[70]	train-mlogloss:0.32997	eval-mlogloss:0.31095
[71]	train-mlogloss:0.32334	eval-mlogloss:0.30331
[72]	train-mlogloss:0.31829	eval-mlogloss:0.29779
[73]	train-mlogloss:0.31481	eval-mlogloss:0.29386
[74]	train-mlogloss:0.31039	eval-mlogloss:0.28912
[75]	train-mlogloss:0.30519	eval-mlogloss:0.28335
[76]	train-mlogloss:0.30255	eval-mlogloss:0.28117
[77]	train-mlogloss:0.30036	eval-mlogloss:0.27929
[78]	train-mlogloss:0.29745	eval-mlogloss:0.27623
[79]	train-mlogloss:0.29537	eval-mlogloss:0.27444
[80]	train-mlogloss:0.29275	eval-mlogloss:0.27193
[81]	train-mlogloss:0.28862	eval-mlogloss:0.26754
[82]	train-mlogloss:0.28662	eval-mlogloss:0.26524
[83]	train-mlogloss:0.28388	eval-mlogloss:0.26191
[84]	train-mlogloss:0.28095	eval-mlogloss:0.25878
[85]	train-mlogloss:0.27732	eval-mlogloss:0.25465
[86]	train-mlogloss:0.27402	eval-mlogloss:0.25031
[87]	train-mlogloss:0.27061	eval-mlogloss:0.24628
[88]	train-mlogloss:0.26759	eval-mlogloss:0.24234
[89]	train-mlogloss:0.26386	eval-mlogloss:0.23826
[90]	train-mlogloss:0.26038	eval-mlogloss:0.23425
[91]	train-mlogloss:0.25850	eval-mlogloss:0.23235
[92]	train-mlogloss:0.25484	eval-mlogloss:0.22825
[93]	train-mlogloss:0.25409	eval-mlogloss:0.22777
[94]	train-mlogloss:0.25008	eval-mlogloss:0.22269
[95]	train-mlogloss:0.24685	eval-mlogloss:0.21835
[96]	train-mlogloss:0.24314	eval-mlogloss:0.21407
[97]	train-mlogloss:0.24129	eval-mlogloss:0.21202
[98]	train-mlogloss:0.23895	eval-mlogloss:0.20915
[99]	train-mlogloss:0.23844	eval-mlogloss:0.20907
[100]	train-mlogloss:0.23582	eval-mlogloss:0.20630
[101]	train-mlogloss:0.23364	eval-mlogloss:0.20370
[102]	train-mlogloss:0.23200	eval-mlogloss:0.20219
[103]	train-mlogloss:0.22852	eval-mlogloss:0.19814
[104]	train-mlogloss:0.22704	eval-mlogloss:0.19644
[105]	train-mlogloss:0.22557	eval-mlogloss:0.19489
[106]	train-mlogloss:0.22389	eval-mlogloss:0.19281
[107]	train-mlogloss:0.22069	eval-mlogloss:0.18855
[108]	train-mlogloss:0.21899	eval-mlogloss:0.18706
[109]	train-mlogloss:0.21596	eval-mlogloss:0.18306
[110]	train-mlogloss:0.21424	eval-mlogloss:0.18085
[111]	train-mlogloss:0.21214	eval-mlogloss:0.17831
[112]	train-mlogloss:0.21054	eval-mlogloss:0.17665
[113]	train-mlogloss:0.20751	eval-mlogloss:0.17266
[114]	train-mlogloss:0.20632	eval-mlogloss:0.17135
[115]	train-mlogloss:0.20467	eval-mlogloss:0.16946
[116]	train-mlogloss:0.20207	eval-mlogloss:0.16624
[117]	train-mlogloss:0.20049	eval-mlogloss:0.16432
[118]	train-mlogloss:0.19886	eval-mlogloss:0.16242
[119]	train-mlogloss:0.19789	eval-mlogloss:0.16134
[120]	train-mlogloss:0.19557	eval-mlogloss:0.15821
[121]	train-mlogloss:0.19363	eval-mlogloss:0.15619
[122]	train-mlogloss:0.19136	eval-mlogloss:0.15318
[123]	train-mlogloss:0.18954	eval-mlogloss:0.15109
[124]	train-mlogloss:0.18798	eval-mlogloss:0.14920
[125]	train-mlogloss:0.18648	eval-mlogloss:0.14723
[126]	train-mlogloss:0.18593	eval-mlogloss:0.14659
[127]	train-mlogloss:0.18486	eval-mlogloss:0.14539
[128]	train-mlogloss:0.18399	eval-mlogloss:0.14418
[129]	train-mlogloss:0.18328	eval-mlogloss:0.14318
[130]	train-mlogloss:0.18301	eval-mlogloss:0.14303
[131]	train-mlogloss:0.18219	eval-mlogloss:0.14182
[132]	train-mlogloss:0.18101	eval-mlogloss:0.14038
[133]	train-mlogloss:0.18068	eval-mlogloss:0.13997
[134]	train-mlogloss:0.18038	eval-mlogloss:0.13967
[135]	train-mlogloss:0.17927	eval-mlogloss:0.13785
[136]	train-mlogloss:0.17878	eval-mlogloss:0.13691
[137]	train-mlogloss:0.17673	eval-mlogloss:0.13464
[138]	train-mlogloss:0.17537	eval-mlogloss:0.13294
[139]	train-mlogloss:0.17483	eval-mlogloss:0.13256
[140]	train-mlogloss:0.17438	eval-mlogloss:0.13179
[141]	train-mlogloss:0.17370	eval-mlogloss:0.13102
[142]	train-mlogloss:0.17318	eval-mlogloss:0.13032
[143]	train-mlogloss:0.17227	eval-mlogloss:0.12906
[144]	train-mlogloss:0.17111	eval-mlogloss:0.12739
[145]	train-mlogloss:0.17077	eval-mlogloss:0.12678
[146]	train-mlogloss:0.17056	eval-mlogloss:0.12646
[147]	train-mlogloss:0.17017	eval-mlogloss:0.12608
[148]	train-mlogloss:0.17000	eval-mlogloss:0.12582
[149]	train-mlogloss:0.16983	eval-mlogloss:0.12558
[150]	train-mlogloss:0.16915	eval-mlogloss:0.12477
[151]	train-mlogloss:0.16871	eval-mlogloss:0.12423
[152]	train-mlogloss:0.16858	eval-mlogloss:0.12403
[153]	train-mlogloss:0.16814	eval-mlogloss:0.12347
[154]	train-mlogloss:0.16721	eval-mlogloss:0.12231
[155]	train-mlogloss:0.16708	eval-mlogloss:0.12215
[156]	train-mlogloss:0.16697	eval-mlogloss:0.12196
[157]	train-mlogloss:0.16683	eval-mlogloss:0.12178
[158]	train-mlogloss:0.16605	eval-mlogloss:0.12072
[159]	train-mlogloss:0.16543	eval-mlogloss:0.11989
[160]	train-mlogloss:0.16491	eval-mlogloss:0.11910
[161]	train-mlogloss:0.16410	eval-mlogloss:0.11795
[162]	train-mlogloss:0.16402	eval-mlogloss:0.11781
[163]	train-mlogloss:0.16388	eval-mlogloss:0.11758
[164]	train-mlogloss:0.16379	eval-mlogloss:0.11746
[165]	train-mlogloss:0.16326	eval-mlogloss:0.11667
[166]	train-mlogloss:0.16249	eval-mlogloss:0.11550
[167]	train-mlogloss:0.16180	eval-mlogloss:0.11443
[168]	train-mlogloss:0.16132	eval-mlogloss:0.11373
[169]	train-mlogloss:0.16109	eval-mlogloss:0.11372
[170]	train-mlogloss:0.16095	eval-mlogloss:0.11379
[171]	train-mlogloss:0.16066	eval-mlogloss:0.11368
[172]	train-mlogloss:0.16053	eval-mlogloss:0.11386
[173]	train-mlogloss:0.16039	eval-mlogloss:0.11392
[174]	train-mlogloss:0.15991	eval-mlogloss:0.11313
[175]	train-mlogloss:0.15965	eval-mlogloss:0.11317
[176]	train-mlogloss:0.15914	eval-mlogloss:0.11257
[177]	train-mlogloss:0.15909	eval-mlogloss:0.11246
[178]	train-mlogloss:0.15856	eval-mlogloss:0.11182
[179]	train-mlogloss:0.15840	eval-mlogloss:0.11179
[180]	train-mlogloss:0.15782	eval-mlogloss:0.11078
[181]	train-mlogloss:0.15717	eval-mlogloss:0.10993
[182]	train-mlogloss:0.15706	eval-mlogloss:0.10984
[183]	train-mlogloss:0.15700	eval-mlogloss:0.10982
[184]	train-mlogloss:0.15659	eval-mlogloss:0.10936
[185]	train-mlogloss:0.15599	eval-mlogloss:0.10838
[186]	train-mlogloss:0.15550	eval-mlogloss:0.10783
[187]	train-mlogloss:0.15533	eval-mlogloss:0.10756
[188]	train-mlogloss:0.15492	eval-mlogloss:0.10691
[189]	train-mlogloss:0.15436	eval-mlogloss:0.10604
[190]	train-mlogloss:0.15417	eval-mlogloss:0.10570
[191]	train-mlogloss:0.15411	eval-mlogloss:0.10565
[192]	train-mlogloss:0.15363	eval-mlogloss:0.10520
[193]	train-mlogloss:0.15316	eval-mlogloss:0.10450
[194]	train-mlogloss:0.15282	eval-mlogloss:0.10411
[195]	train-mlogloss:0.15241	eval-mlogloss:0.10359
[196]	train-mlogloss:0.15205	eval-mlogloss:0.10339
[197]	train-mlogloss:0.15150	eval-mlogloss:0.10245
[198]	train-mlogloss:0.15143	eval-mlogloss:0.10239
[199]	train-mlogloss:0.15125	eval-mlogloss:0.10247
[200]	train-mlogloss:0.15122	eval-mlogloss:0.10244
[201]	train-mlogloss:0.15121	eval-mlogloss:0.10220
[202]	train-mlogloss:0.15115	eval-mlogloss:0.10209
[203]	train-mlogloss:0.15074	eval-mlogloss:0.10156
[204]	train-mlogloss:0.15064	eval-mlogloss:0.10147
[205]	train-mlogloss:0.15059	eval-mlogloss:0.10135
[206]	train-mlogloss:0.15015	eval-mlogloss:0.10084
[207]	train-mlogloss:0.15004	eval-mlogloss:0.10074
[208]	train-mlogloss:0.14969	eval-mlogloss:0.10034
[209]	train-mlogloss:0.14945	eval-mlogloss:0.09995
[210]	train-mlogloss:0.14936	eval-mlogloss:0.10003
[211]	train-mlogloss:0.14925	eval-mlogloss:0.10019
[212]	train-mlogloss:0.14893	eval-mlogloss:0.09965
[213]	train-mlogloss:0.14867	eval-mlogloss:0.09922
[214]	train-mlogloss:0.14835	eval-mlogloss:0.09885
[215]	train-mlogloss:0.14802	eval-mlogloss:0.09828
[216]	train-mlogloss:0.14783	eval-mlogloss:0.09834
[217]	train-mlogloss:0.14780	eval-mlogloss:0.09826
[218]	train-mlogloss:0.14756	eval-mlogloss:0.09835
[219]	train-mlogloss:0.14755	eval-mlogloss:0.09835
[220]	train-mlogloss:0.14747	eval-mlogloss:0.09833
[221]	train-mlogloss:0.14731	eval-mlogloss:0.09816
[222]	train-mlogloss:0.14708	eval-mlogloss:0.09780
[223]	train-mlogloss:0.14706	eval-mlogloss:0.09781
[224]	train-mlogloss:0.14666	eval-mlogloss:0.09731
[225]	train-mlogloss:0.14652	eval-mlogloss:0.09717
[226]	train-mlogloss:0.14652	eval-mlogloss:0.09717
[227]	train-mlogloss:0.14633	eval-mlogloss:0.09727
[228]	train-mlogloss:0.14598	eval-mlogloss:0.09665
[229]	train-mlogloss:0.14565	eval-mlogloss:0.09608
[230]	train-mlogloss:0.14556	eval-mlogloss:0.09596
[231]	train-mlogloss:0.14554	eval-mlogloss:0.09588
[232]	train-mlogloss:0.14537	eval-mlogloss:0.09595
[233]	train-mlogloss:0.14500	eval-mlogloss:0.09538
[234]	train-mlogloss:0.14475	eval-mlogloss:0.09499
[235]	train-mlogloss:0.14474	eval-mlogloss:0.09498
[236]	train-mlogloss:0.14463	eval-mlogloss:0.09507
[237]	train-mlogloss:0.14456	eval-mlogloss:0.09497
[238]	train-mlogloss:0.14455	eval-mlogloss:0.09500
[239]	train-mlogloss:0.14444	eval-mlogloss:0.09509
[240]	train-mlogloss:0.14439	eval-mlogloss:0.09501
[241]	train-mlogloss:0.14407	eval-mlogloss:0.09459
[242]	train-mlogloss:0.14383	eval-mlogloss:0.09416
[243]	train-mlogloss:0.14378	eval-mlogloss:0.09408
[244]	train-mlogloss:0.14365	eval-mlogloss:0.09423
[245]	train-mlogloss:0.14357	eval-mlogloss:0.09414
[246]	train-mlogloss:0.14357	eval-mlogloss:0.09410
[247]	train-mlogloss:0.14348	eval-mlogloss:0.09397
[248]	train-mlogloss:0.14339	eval-mlogloss:0.09403
[249]	train-mlogloss:0.14306	eval-mlogloss:0.09347
[250]	train-mlogloss:0.14275	eval-mlogloss:0.09294
[251]	train-mlogloss:0.14270	eval-mlogloss:0.09292
[252]	train-mlogloss:0.14261	eval-mlogloss:0.09304
[253]	train-mlogloss:0.14248	eval-mlogloss:0.09281
[254]	train-mlogloss:0.14242	eval-mlogloss:0.09286
[255]	train-mlogloss:0.14232	eval-mlogloss:0.09296
[256]	train-mlogloss:0.14198	eval-mlogloss:0.09244
[257]	train-mlogloss:0.14198	eval-mlogloss:0.09246
[258]	train-mlogloss:0.14188	eval-mlogloss:0.09223
[259]	train-mlogloss:0.14189	eval-mlogloss:0.09239
[260]	train-mlogloss:0.14188	eval-mlogloss:0.09239
[261]	train-mlogloss:0.14183	eval-mlogloss:0.09227
[262]	train-mlogloss:0.14157	eval-mlogloss:0.09194
[263]	train-mlogloss:0.14152	eval-mlogloss:0.09192
[264]	train-mlogloss:0.14139	eval-mlogloss:0.09193
[265]	train-mlogloss:0.14129	eval-mlogloss:0.09184
[266]	train-mlogloss:0.14128	eval-mlogloss:0.09179
[267]	train-mlogloss:0.14113	eval-mlogloss:0.09162
[268]	train-mlogloss:0.14093	eval-mlogloss:0.09127
[269]	train-mlogloss:0.14077	eval-mlogloss:0.09097
[270]	train-mlogloss:0.14046	eval-mlogloss:0.09044
[271]	train-mlogloss:0.14040	eval-mlogloss:0.09049
[272]	train-mlogloss:0.14036	eval-mlogloss:0.09041
[273]	train-mlogloss:0.14027	eval-mlogloss:0.09026
[274]	train-mlogloss:0.14020	eval-mlogloss:0.09012
[275]	train-mlogloss:0.13990	eval-mlogloss:0.08971
[276]	train-mlogloss:0.13987	eval-mlogloss:0.08965
[277]	train-mlogloss:0.13987	eval-mlogloss:0.08968
[278]	train-mlogloss:0.13984	eval-mlogloss:0.08962
[279]	train-mlogloss:0.13946	eval-mlogloss:0.08917
[280]	train-mlogloss:0.13944	eval-mlogloss:0.08921
[281]	train-mlogloss:0.13928	eval-mlogloss:0.08890
[282]	train-mlogloss:0.13926	eval-mlogloss:0.08888
[283]	train-mlogloss:0.13920	eval-mlogloss:0.08881
[284]	train-mlogloss:0.13920	eval-mlogloss:0.08880
[285]	train-mlogloss:0.13907	eval-mlogloss:0.08864
[286]	train-mlogloss:0.13891	eval-mlogloss:0.08828
[287]	train-mlogloss:0.13879	eval-mlogloss:0.08805
[288]	train-mlogloss:0.13874	eval-mlogloss:0.08795
[289]	train-mlogloss:0.13871	eval-mlogloss:0.08791
[290]	train-mlogloss:0.13838	eval-mlogloss:0.08736
[291]	train-mlogloss:0.13828	eval-mlogloss:0.08705
[292]	train-mlogloss:0.13824	eval-mlogloss:0.08698
[293]	train-mlogloss:0.13811	eval-mlogloss:0.08706
[294]	train-mlogloss:0.13789	eval-mlogloss:0.08677
[295]	train-mlogloss:0.13780	eval-mlogloss:0.08670
[296]	train-mlogloss:0.13765	eval-mlogloss:0.08652
[297]	train-mlogloss:0.13761	eval-mlogloss:0.08644
[298]	train-mlogloss:0.13760	eval-mlogloss:0.08640
[299]	train-mlogloss:0.13757	eval-mlogloss:0.08637

[I 2026-03-04 10:34:35,578] Trial 5 finished with value: 1.0 and parameters: {'lambda': 1.5219707207241334e-07, 'alpha': 8.645195355029072e-08, 'eta': 0.027007828378232755, 'gamma': 0.02911698046947663, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.8048913942211432, 'colsample_bytree': 0.4212007689350048}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.99147	eval-mlogloss:0.99999
[1]	train-mlogloss:0.85866	eval-mlogloss:0.85881

[I 2026-03-04 10:34:35,629] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.92479	eval-mlogloss:0.92281
[1]	train-mlogloss:0.78606	eval-mlogloss:0.78302

[I 2026-03-04 10:34:35,698] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93801	eval-mlogloss:0.92990
[1]	train-mlogloss:0.81888	eval-mlogloss:0.80832

[I 2026-03-04 10:34:35,736] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96010	eval-mlogloss:0.95097
[1]	train-mlogloss:0.85229	eval-mlogloss:0.82290

[I 2026-03-04 10:34:35,783] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08828	eval-mlogloss:1.09092
[1]	train-mlogloss:1.06663	eval-mlogloss:1.06814
[2]	train-mlogloss:1.04462	eval-mlogloss:1.04417
[3]	train-mlogloss:1.02880	eval-mlogloss:1.02643
[4]	train-mlogloss:1.01214	eval-mlogloss:1.01024
[5]	train-mlogloss:0.99119	eval-mlogloss:0.98817
[6]	train-mlogloss:0.97620	eval-mlogloss:0.97222
[7]	train-mlogloss:0.96561	eval-mlogloss:0.96272
[8]	train-mlogloss:0.94698	eval-mlogloss:0.94267
[9]	train-mlogloss:0.93267	eval-mlogloss:0.92835
[10]	train-mlogloss:0.91557	eval-mlogloss:0.91134
[11]	train-mlogloss:0.90067	eval-mlogloss:0.89606
[12]	train-mlogloss:0.89433	eval-mlogloss:0.88943
[13]	train-mlogloss:0.87849	eval-mlogloss:0.87224
[14]	train-mlogloss:0.87359	eval-mlogloss:0.86767
[15]	train-mlogloss:0.86366	eval-mlogloss:0.85814
[16]	train-mlogloss:0.85285	eval-mlogloss:0.84686
[17]	train-mlogloss:0.84070	eval-mlogloss:0.83512
[18]	train-mlogloss:0.83221	eval-mlogloss:0.82642
[19]	train-mlogloss:0.82366	eval-mlogloss:0.81762
[20]	train-mlogloss:0.80962	eval-mlogloss:0.80253
[21]	train-mlogloss:0.79915	eval-mlogloss:0.79088
[22]	train-mlogloss:0.79080	eval-mlogloss:0.78195
[23]	train-mlogloss:0.77666	eval-mlogloss:0.76644
[24]	train-mlogloss:0.76848	eval-mlogloss:0.75743
[25]	train-mlogloss:0.75871	eval-mlogloss:0.74636
[26]	train-mlogloss:0.74806	eval-mlogloss:0.73594
[27]	train-mlogloss:0.74491	eval-mlogloss:0.73394
[28]	train-mlogloss:0.74073	eval-mlogloss:0.73110
[29]	train-mlogloss:0.73071	eval-mlogloss:0.71979
[30]	train-mlogloss:0.72151	eval-mlogloss:0.71030
[31]	train-mlogloss:0.71819	eval-mlogloss:0.70699
[32]	train-mlogloss:0.71206	eval-mlogloss:0.70129
[33]	train-mlogloss:0.70614	eval-mlogloss:0.69427
[34]	train-mlogloss:0.69529	eval-mlogloss:0.68228
[35]	train-mlogloss:0.68834	eval-mlogloss:0.67520
[36]	train-mlogloss:0.68280	eval-mlogloss:0.67051
[37]	train-mlogloss:0.67526	eval-mlogloss:0.66293
[38]	train-mlogloss:0.66687	eval-mlogloss:0.65417
[39]	train-mlogloss:0.65991	eval-mlogloss:0.64728
[40]	train-mlogloss:0.65674	eval-mlogloss:0.64450
[41]	train-mlogloss:0.64940	eval-mlogloss:0.63626
[42]	train-mlogloss:0.64704	eval-mlogloss:0.63476
[43]	train-mlogloss:0.63974	eval-mlogloss:0.62724
[44]	train-mlogloss:0.63157	eval-mlogloss:0.61867
[45]	train-mlogloss:0.62757	eval-mlogloss:0.61439
[46]	train-mlogloss:0.62030	eval-mlogloss:0.60581
[47]	train-mlogloss:0.61548	eval-mlogloss:0.60147
[48]	train-mlogloss:0.60751	eval-mlogloss:0.59293
[49]	train-mlogloss:0.60012	eval-mlogloss:0.58523
[50]	train-mlogloss:0.59249	eval-mlogloss:0.57670
[51]	train-mlogloss:0.58789	eval-mlogloss:0.57239
[52]	train-mlogloss:0.58398	eval-mlogloss:0.56971
[53]	train-mlogloss:0.57539	eval-mlogloss:0.55999
[54]	train-mlogloss:0.57147	eval-mlogloss:0.55582
[55]	train-mlogloss:0.56288	eval-mlogloss:0.54674
[56]	train-mlogloss:0.55619	eval-mlogloss:0.53952
[57]	train-mlogloss:0.54807	eval-mlogloss:0.53048
[58]	train-mlogloss:0.54431	eval-mlogloss:0.52626
[59]	train-mlogloss:0.54229	eval-mlogloss:0.52436
[60]	train-mlogloss:0.53707	eval-mlogloss:0.51869
[61]	train-mlogloss:0.53260	eval-mlogloss:0.51420
[62]	train-mlogloss:0.52504	eval-mlogloss:0.50613
[63]	train-mlogloss:0.52156	eval-mlogloss:0.50205
[64]	train-mlogloss:0.51922	eval-mlogloss:0.49999
[65]	train-mlogloss:0.51499	eval-mlogloss:0.49534
[66]	train-mlogloss:0.50937	eval-mlogloss:0.48954
[67]	train-mlogloss:0.50504	eval-mlogloss:0.48514
[68]	train-mlogloss:0.50292	eval-mlogloss:0.48343
[69]	train-mlogloss:0.49656	eval-mlogloss:0.47634
[70]	train-mlogloss:0.49230	eval-mlogloss:0.47180
[71]	train-mlogloss:0.48509	eval-mlogloss:0.46408
[72]	train-mlogloss:0.47991	eval-mlogloss:0.45871
[73]	train-mlogloss:0.47593	eval-mlogloss:0.45451
[74]	train-mlogloss:0.47122	eval-mlogloss:0.44980
[75]	train-mlogloss:0.46535	eval-mlogloss:0.44278
[76]	train-mlogloss:0.46195	eval-mlogloss:0.43946
[77]	train-mlogloss:0.45935	eval-mlogloss:0.43714
[78]	train-mlogloss:0.45633	eval-mlogloss:0.43431
[79]	train-mlogloss:0.45361	eval-mlogloss:0.43232
[80]	train-mlogloss:0.45077	eval-mlogloss:0.42906
[81]	train-mlogloss:0.44602	eval-mlogloss:0.42424
[82]	train-mlogloss:0.44291	eval-mlogloss:0.42126
[83]	train-mlogloss:0.43852	eval-mlogloss:0.41606
[84]	train-mlogloss:0.43540	eval-mlogloss:0.41263
[85]	train-mlogloss:0.43105	eval-mlogloss:0.40771
[86]	train-mlogloss:0.42692	eval-mlogloss:0.40330
[87]	train-mlogloss:0.42285	eval-mlogloss:0.39895
[88]	train-mlogloss:0.41959	eval-mlogloss:0.39499
[89]	train-mlogloss:0.41535	eval-mlogloss:0.39046
[90]	train-mlogloss:0.41135	eval-mlogloss:0.38585
[91]	train-mlogloss:0.40883	eval-mlogloss:0.38319
[92]	train-mlogloss:0.40386	eval-mlogloss:0.37770
[93]	train-mlogloss:0.40252	eval-mlogloss:0.37604
[94]	train-mlogloss:0.39797	eval-mlogloss:0.37083
[95]	train-mlogloss:0.39391	eval-mlogloss:0.36609
[96]	train-mlogloss:0.38928	eval-mlogloss:0.36098
[97]	train-mlogloss:0.38717	eval-mlogloss:0.35895
[98]	train-mlogloss:0.38454	eval-mlogloss:0.35597
[99]	train-mlogloss:0.38353	eval-mlogloss:0.35563
[100]	train-mlogloss:0.38032	eval-mlogloss:0.35242
[101]	train-mlogloss:0.37720	eval-mlogloss:0.34898
[102]	train-mlogloss:0.37540	eval-mlogloss:0.34715
[103]	train-mlogloss:0.37073	eval-mlogloss:0.34173
[104]	train-mlogloss:0.36835	eval-mlogloss:0.33892
[105]	train-mlogloss:0.36658	eval-mlogloss:0.33687
[106]	train-mlogloss:0.36354	eval-mlogloss:0.33377
[107]	train-mlogloss:0.35907	eval-mlogloss:0.32864
[108]	train-mlogloss:0.35698	eval-mlogloss:0.32632
[109]	train-mlogloss:0.35301	eval-mlogloss:0.32178
[110]	train-mlogloss:0.35076	eval-mlogloss:0.31919
[111]	train-mlogloss:0.34778	eval-mlogloss:0.31595
[112]	train-mlogloss:0.34570	eval-mlogloss:0.31380
[113]	train-mlogloss:0.34188	eval-mlogloss:0.30938
[114]	train-mlogloss:0.34024	eval-mlogloss:0.30740
[115]	train-mlogloss:0.33785	eval-mlogloss:0.30492
[116]	train-mlogloss:0.33410	eval-mlogloss:0.30069
[117]	train-mlogloss:0.33144	eval-mlogloss:0.29817
[118]	train-mlogloss:0.32900	eval-mlogloss:0.29554
[119]	train-mlogloss:0.32717	eval-mlogloss:0.29348
[120]	train-mlogloss:0.32377	eval-mlogloss:0.28981
[121]	train-mlogloss:0.32077	eval-mlogloss:0.28669
[122]	train-mlogloss:0.31748	eval-mlogloss:0.28286
[123]	train-mlogloss:0.31475	eval-mlogloss:0.27960
[124]	train-mlogloss:0.31241	eval-mlogloss:0.27699
[125]	train-mlogloss:0.31011	eval-mlogloss:0.27431
[126]	train-mlogloss:0.30838	eval-mlogloss:0.27260
[127]	train-mlogloss:0.30684	eval-mlogloss:0.27108
[128]	train-mlogloss:0.30462	eval-mlogloss:0.26843
[129]	train-mlogloss:0.30285	eval-mlogloss:0.26638
[130]	train-mlogloss:0.30244	eval-mlogloss:0.26629
[131]	train-mlogloss:0.29901	eval-mlogloss:0.26205
[132]	train-mlogloss:0.29650	eval-mlogloss:0.25931
[133]	train-mlogloss:0.29471	eval-mlogloss:0.25731
[134]	train-mlogloss:0.29355	eval-mlogloss:0.25606
[135]	train-mlogloss:0.29140	eval-mlogloss:0.25345
[136]	train-mlogloss:0.28973	eval-mlogloss:0.25185
[137]	train-mlogloss:0.28699	eval-mlogloss:0.24902
[138]	train-mlogloss:0.28509	eval-mlogloss:0.24702
[139]	train-mlogloss:0.28388	eval-mlogloss:0.24592
[140]	train-mlogloss:0.28227	eval-mlogloss:0.24411
[141]	train-mlogloss:0.28053	eval-mlogloss:0.24237
[142]	train-mlogloss:0.27860	eval-mlogloss:0.24026
[143]	train-mlogloss:0.27594	eval-mlogloss:0.23728
[144]	train-mlogloss:0.27368	eval-mlogloss:0.23467
[145]	train-mlogloss:0.27175	eval-mlogloss:0.23220
[146]	train-mlogloss:0.27037	eval-mlogloss:0.23070
[147]	train-mlogloss:0.26889	eval-mlogloss:0.22917
[148]	train-mlogloss:0.26699	eval-mlogloss:0.22692
[149]	train-mlogloss:0.26656	eval-mlogloss:0.22660
[150]	train-mlogloss:0.26429	eval-mlogloss:0.22418
[151]	train-mlogloss:0.26227	eval-mlogloss:0.22185
[152]	train-mlogloss:0.26146	eval-mlogloss:0.22091
[153]	train-mlogloss:0.26008	eval-mlogloss:0.21975
[154]	train-mlogloss:0.25770	eval-mlogloss:0.21713
[155]	train-mlogloss:0.25624	eval-mlogloss:0.21555
[156]	train-mlogloss:0.25454	eval-mlogloss:0.21366
[157]	train-mlogloss:0.25337	eval-mlogloss:0.21247
[158]	train-mlogloss:0.25166	eval-mlogloss:0.21067
[159]	train-mlogloss:0.25066	eval-mlogloss:0.20960
[160]	train-mlogloss:0.24917	eval-mlogloss:0.20790
[161]	train-mlogloss:0.24692	eval-mlogloss:0.20534
[162]	train-mlogloss:0.24571	eval-mlogloss:0.20399
[163]	train-mlogloss:0.24481	eval-mlogloss:0.20301
[164]	train-mlogloss:0.24455	eval-mlogloss:0.20254
[165]	train-mlogloss:0.24368	eval-mlogloss:0.20161
[166]	train-mlogloss:0.24168	eval-mlogloss:0.19946
[167]	train-mlogloss:0.23969	eval-mlogloss:0.19716
[168]	train-mlogloss:0.23847	eval-mlogloss:0.19571
[169]	train-mlogloss:0.23776	eval-mlogloss:0.19502
[170]	train-mlogloss:0.23754	eval-mlogloss:0.19485
[171]	train-mlogloss:0.23630	eval-mlogloss:0.19355
[172]	train-mlogloss:0.23595	eval-mlogloss:0.19321
[173]	train-mlogloss:0.23530	eval-mlogloss:0.19251
[174]	train-mlogloss:0.23424	eval-mlogloss:0.19111
[175]	train-mlogloss:0.23370	eval-mlogloss:0.19072
[176]	train-mlogloss:0.23251	eval-mlogloss:0.18948
[177]	train-mlogloss:0.23193	eval-mlogloss:0.18898
[178]	train-mlogloss:0.23067	eval-mlogloss:0.18763
[179]	train-mlogloss:0.23023	eval-mlogloss:0.18723
[180]	train-mlogloss:0.22923	eval-mlogloss:0.18608
[181]	train-mlogloss:0.22800	eval-mlogloss:0.18505
[182]	train-mlogloss:0.22732	eval-mlogloss:0.18426
[183]	train-mlogloss:0.22697	eval-mlogloss:0.18427
[184]	train-mlogloss:0.22580	eval-mlogloss:0.18286
[185]	train-mlogloss:0.22474	eval-mlogloss:0.18166
[186]	train-mlogloss:0.22355	eval-mlogloss:0.18046
[187]	train-mlogloss:0.22240	eval-mlogloss:0.17924
[188]	train-mlogloss:0.22093	eval-mlogloss:0.17729
[189]	train-mlogloss:0.21923	eval-mlogloss:0.17540
[190]	train-mlogloss:0.21846	eval-mlogloss:0.17456
[191]	train-mlogloss:0.21747	eval-mlogloss:0.17339
[192]	train-mlogloss:0.21670	eval-mlogloss:0.17253
[193]	train-mlogloss:0.21582	eval-mlogloss:0.17155
[194]	train-mlogloss:0.21474	eval-mlogloss:0.17028
[195]	train-mlogloss:0.21327	eval-mlogloss:0.16859
[196]	train-mlogloss:0.21218	eval-mlogloss:0.16753
[197]	train-mlogloss:0.21038	eval-mlogloss:0.16516
[198]	train-mlogloss:0.20992	eval-mlogloss:0.16463
[199]	train-mlogloss:0.20935	eval-mlogloss:0.16411
[200]	train-mlogloss:0.20822	eval-mlogloss:0.16292
[201]	train-mlogloss:0.20764	eval-mlogloss:0.16235
[202]	train-mlogloss:0.20720	eval-mlogloss:0.16197
[203]	train-mlogloss:0.20609	eval-mlogloss:0.16080
[204]	train-mlogloss:0.20554	eval-mlogloss:0.16027
[205]	train-mlogloss:0.20521	eval-mlogloss:0.15994
[206]	train-mlogloss:0.20453	eval-mlogloss:0.15936
[207]	train-mlogloss:0.20384	eval-mlogloss:0.15869
[208]	train-mlogloss:0.20279	eval-mlogloss:0.15767
[209]	train-mlogloss:0.20141	eval-mlogloss:0.15605
[210]	train-mlogloss:0.20129	eval-mlogloss:0.15592
[211]	train-mlogloss:0.20086	eval-mlogloss:0.15550
[212]	train-mlogloss:0.20001	eval-mlogloss:0.15446
[213]	train-mlogloss:0.19909	eval-mlogloss:0.15347
[214]	train-mlogloss:0.19806	eval-mlogloss:0.15242
[215]	train-mlogloss:0.19665	eval-mlogloss:0.15070
[216]	train-mlogloss:0.19618	eval-mlogloss:0.15037
[217]	train-mlogloss:0.19497	eval-mlogloss:0.14881
[218]	train-mlogloss:0.19473	eval-mlogloss:0.14870
[219]	train-mlogloss:0.19323	eval-mlogloss:0.14700
[220]	train-mlogloss:0.19281	eval-mlogloss:0.14650
[221]	train-mlogloss:0.19238	eval-mlogloss:0.14613
[222]	train-mlogloss:0.19187	eval-mlogloss:0.14560
[223]	train-mlogloss:0.19152	eval-mlogloss:0.14538
[224]	train-mlogloss:0.19046	eval-mlogloss:0.14429
[225]	train-mlogloss:0.19033	eval-mlogloss:0.14414
[226]	train-mlogloss:0.18982	eval-mlogloss:0.14362
[227]	train-mlogloss:0.18932	eval-mlogloss:0.14308
[228]	train-mlogloss:0.18853	eval-mlogloss:0.14228
[229]	train-mlogloss:0.18789	eval-mlogloss:0.14165
[230]	train-mlogloss:0.18780	eval-mlogloss:0.14159
[231]	train-mlogloss:0.18731	eval-mlogloss:0.14110
[232]	train-mlogloss:0.18715	eval-mlogloss:0.14103
[233]	train-mlogloss:0.18655	eval-mlogloss:0.14038
[234]	train-mlogloss:0.18545	eval-mlogloss:0.13891
[235]	train-mlogloss:0.18467	eval-mlogloss:0.13790
[236]	train-mlogloss:0.18417	eval-mlogloss:0.13730
[237]	train-mlogloss:0.18340	eval-mlogloss:0.13648
[238]	train-mlogloss:0.18277	eval-mlogloss:0.13577
[239]	train-mlogloss:0.18197	eval-mlogloss:0.13484
[240]	train-mlogloss:0.18093	eval-mlogloss:0.13359
[241]	train-mlogloss:0.18049	eval-mlogloss:0.13327
[242]	train-mlogloss:0.18013	eval-mlogloss:0.13279
[243]	train-mlogloss:0.17983	eval-mlogloss:0.13240
[244]	train-mlogloss:0.17944	eval-mlogloss:0.13211
[245]	train-mlogloss:0.17891	eval-mlogloss:0.13158
[246]	train-mlogloss:0.17885	eval-mlogloss:0.13154
[247]	train-mlogloss:0.17866	eval-mlogloss:0.13138
[248]	train-mlogloss:0.17864	eval-mlogloss:0.13137
[249]	train-mlogloss:0.17816	eval-mlogloss:0.13074
[250]	train-mlogloss:0.17752	eval-mlogloss:0.12993
[251]	train-mlogloss:0.17709	eval-mlogloss:0.12943
[252]	train-mlogloss:0.17688	eval-mlogloss:0.12926
[253]	train-mlogloss:0.17658	eval-mlogloss:0.12904
[254]	train-mlogloss:0.17606	eval-mlogloss:0.12846
[255]	train-mlogloss:0.17576	eval-mlogloss:0.12831
[256]	train-mlogloss:0.17527	eval-mlogloss:0.12783
[257]	train-mlogloss:0.17479	eval-mlogloss:0.12723
[258]	train-mlogloss:0.17440	eval-mlogloss:0.12687
[259]	train-mlogloss:0.17435	eval-mlogloss:0.12684
[260]	train-mlogloss:0.17410	eval-mlogloss:0.12691
[261]	train-mlogloss:0.17351	eval-mlogloss:0.12621
[262]	train-mlogloss:0.17304	eval-mlogloss:0.12567
[263]	train-mlogloss:0.17235	eval-mlogloss:0.12489
[264]	train-mlogloss:0.17231	eval-mlogloss:0.12494
[265]	train-mlogloss:0.17187	eval-mlogloss:0.12457
[266]	train-mlogloss:0.17125	eval-mlogloss:0.12384
[267]	train-mlogloss:0.17087	eval-mlogloss:0.12357
[268]	train-mlogloss:0.17055	eval-mlogloss:0.12313
[269]	train-mlogloss:0.16982	eval-mlogloss:0.12205
[270]	train-mlogloss:0.16910	eval-mlogloss:0.12122
[271]	train-mlogloss:0.16878	eval-mlogloss:0.12095
[272]	train-mlogloss:0.16784	eval-mlogloss:0.11983
[273]	train-mlogloss:0.16756	eval-mlogloss:0.11955
[274]	train-mlogloss:0.16731	eval-mlogloss:0.11938
[275]	train-mlogloss:0.16636	eval-mlogloss:0.11820
[276]	train-mlogloss:0.16608	eval-mlogloss:0.11776
[277]	train-mlogloss:0.16570	eval-mlogloss:0.11730
[278]	train-mlogloss:0.16527	eval-mlogloss:0.11679
[279]	train-mlogloss:0.16458	eval-mlogloss:0.11604
[280]	train-mlogloss:0.16407	eval-mlogloss:0.11527
[281]	train-mlogloss:0.16370	eval-mlogloss:0.11492
[282]	train-mlogloss:0.16293	eval-mlogloss:0.11394
[283]	train-mlogloss:0.16280	eval-mlogloss:0.11389
[284]	train-mlogloss:0.16228	eval-mlogloss:0.11323
[285]	train-mlogloss:0.16214	eval-mlogloss:0.11314
[286]	train-mlogloss:0.16154	eval-mlogloss:0.11239
[287]	train-mlogloss:0.16088	eval-mlogloss:0.11159
[288]	train-mlogloss:0.16054	eval-mlogloss:0.11125
[289]	train-mlogloss:0.15994	eval-mlogloss:0.11057
[290]	train-mlogloss:0.15956	eval-mlogloss:0.11014
[291]	train-mlogloss:0.15911	eval-mlogloss:0.10957
[292]	train-mlogloss:0.15900	eval-mlogloss:0.10961
[293]	train-mlogloss:0.15875	eval-mlogloss:0.10945
[294]	train-mlogloss:0.15820	eval-mlogloss:0.10877
[295]	train-mlogloss:0.15795	eval-mlogloss:0.10850
[296]	train-mlogloss:0.15772	eval-mlogloss:0.10829
[297]	train-mlogloss:0.15711	eval-mlogloss:0.10757
[298]	train-mlogloss:0.15686	eval-mlogloss:0.10721
[299]	train-mlogloss:0.15639	eval-mlogloss:0.10690

[I 2026-03-04 10:34:41,186] Trial 10 finished with value: 1.0 and parameters: {'lambda': 0.00035225955880419075, 'alpha': 0.6892309943149002, 'eta': 0.018869280383959713, 'gamma': 0.001144756691787457, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.407611301522268, 'colsample_bytree': 0.4124969267113958}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.92090	eval-mlogloss:0.91902
[1]	train-mlogloss:0.72652	eval-mlogloss:0.71537

[I 2026-03-04 10:34:41,773] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90263	eval-mlogloss:0.89260
[1]	train-mlogloss:0.69931	eval-mlogloss:0.68003

[I 2026-03-04 10:34:41,940] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03839	eval-mlogloss:1.04196
[1]	train-mlogloss:0.96094	eval-mlogloss:0.96092
[2]	train-mlogloss:0.89063	eval-mlogloss:0.88807
[3]	train-mlogloss:0.82620	eval-mlogloss:0.82169
[4]	train-mlogloss:0.76971	eval-mlogloss:0.76376
[5]	train-mlogloss:0.71704	eval-mlogloss:0.70714
[6]	train-mlogloss:0.67068	eval-mlogloss:0.65961
[7]	train-mlogloss:0.62819	eval-mlogloss:0.61571

[I 2026-03-04 10:34:42,949] Trial 13 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.88369	eval-mlogloss:0.87781
[1]	train-mlogloss:0.66627	eval-mlogloss:0.64940

[I 2026-03-04 10:34:43,975] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05406	eval-mlogloss:1.05637
[1]	train-mlogloss:0.95244	eval-mlogloss:0.94930

[I 2026-03-04 10:34:44,221] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88204	eval-mlogloss:0.86520
[1]	train-mlogloss:0.72390	eval-mlogloss:0.70417

[I 2026-03-04 10:34:44,600] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98970	eval-mlogloss:0.98884
[1]	train-mlogloss:0.86936	eval-mlogloss:0.86318

[I 2026-03-04 10:34:44,722] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.76877	eval-mlogloss:0.74625
[1]	train-mlogloss:0.59339	eval-mlogloss:0.56261

[I 2026-03-04 10:34:44,777] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07214	eval-mlogloss:1.07607
[1]	train-mlogloss:1.00990	eval-mlogloss:1.01094
[2]	train-mlogloss:0.95235	eval-mlogloss:0.95022
[3]	train-mlogloss:0.91209	eval-mlogloss:0.90584
[4]	train-mlogloss:0.87073	eval-mlogloss:0.86242
[5]	train-mlogloss:0.82460	eval-mlogloss:0.81335
[6]	train-mlogloss:0.79142	eval-mlogloss:0.78065
[7]	train-mlogloss:0.76587	eval-mlogloss:0.75650

[I 2026-03-04 10:34:44,892] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.92664	eval-mlogloss:0.92156
[1]	train-mlogloss:0.74722	eval-mlogloss:0.73109

[I 2026-03-04 10:34:44,956] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98330	eval-mlogloss:0.97582
[1]	train-mlogloss:0.88621	eval-mlogloss:0.87017

[I 2026-03-04 10:34:45,019] Trial 21 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02921	eval-mlogloss:1.02519
[1]	train-mlogloss:0.96683	eval-mlogloss:0.95925
[2]	train-mlogloss:0.90912	eval-mlogloss:0.89906
[3]	train-mlogloss:0.85411	eval-mlogloss:0.84246
[4]	train-mlogloss:0.80548	eval-mlogloss:0.79167
[5]	train-mlogloss:0.75927	eval-mlogloss:0.74189
[6]	train-mlogloss:0.71789	eval-mlogloss:0.69847
[7]	train-mlogloss:0.68029	eval-mlogloss:0.65823

[I 2026-03-04 10:34:45,131] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07893	eval-mlogloss:1.07891
[1]	train-mlogloss:1.02829	eval-mlogloss:1.02598
[2]	train-mlogloss:0.98104	eval-mlogloss:0.97628
[3]	train-mlogloss:0.94712	eval-mlogloss:0.93801
[4]	train-mlogloss:0.91249	eval-mlogloss:0.90141
[5]	train-mlogloss:0.87217	eval-mlogloss:0.85881
[6]	train-mlogloss:0.84362	eval-mlogloss:0.83064
[7]	train-mlogloss:0.82302	eval-mlogloss:0.81056

[I 2026-03-04 10:34:45,336] Trial 23 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08479	eval-mlogloss:1.08596
[1]	train-mlogloss:1.07137	eval-mlogloss:1.07189
[2]	train-mlogloss:1.05813	eval-mlogloss:1.05811
[3]	train-mlogloss:1.04453	eval-mlogloss:1.04418
[4]	train-mlogloss:1.03188	eval-mlogloss:1.03101
[5]	train-mlogloss:1.01869	eval-mlogloss:1.01720
[6]	train-mlogloss:1.00603	eval-mlogloss:1.00379
[7]	train-mlogloss:0.99421	eval-mlogloss:0.99160
[8]	train-mlogloss:0.98239	eval-mlogloss:0.97896
[9]	train-mlogloss:0.97058	eval-mlogloss:0.96627
[10]	train-mlogloss:0.95911	eval-mlogloss:0.95450
[11]	train-mlogloss:0.94774	eval-mlogloss:0.94228
[12]	train-mlogloss:0.93770	eval-mlogloss:0.93227
[13]	train-mlogloss:0.92670	eval-mlogloss:0.92064
[14]	train-mlogloss:0.91569	eval-mlogloss:0.90898
[15]	train-mlogloss:0.90502	eval-mlogloss:0.89784
[16]	train-mlogloss:0.89443	eval-mlogloss:0.88658
[17]	train-mlogloss:0.88440	eval-mlogloss:0.87590
[18]	train-mlogloss:0.87520	eval-mlogloss:0.86688
[19]	train-mlogloss:0.86516	eval-mlogloss:0.85619
[20]	train-mlogloss:0.85530	eval-mlogloss:0.84554
[21]	train-mlogloss:0.84707	eval-mlogloss:0.83718
[22]	train-mlogloss:0.83746	eval-mlogloss:0.82708
[23]	train-mlogloss:0.82791	eval-mlogloss:0.81709
[24]	train-mlogloss:0.81981	eval-mlogloss:0.80873
[25]	train-mlogloss:0.81069	eval-mlogloss:0.79909
[26]	train-mlogloss:0.80163	eval-mlogloss:0.78921
[27]	train-mlogloss:0.79302	eval-mlogloss:0.78032
[28]	train-mlogloss:0.78408	eval-mlogloss:0.77085
[29]	train-mlogloss:0.77536	eval-mlogloss:0.76136
[30]	train-mlogloss:0.76711	eval-mlogloss:0.75267
[31]	train-mlogloss:0.75878	eval-mlogloss:0.74355
[32]	train-mlogloss:0.75063	eval-mlogloss:0.73476
[33]	train-mlogloss:0.74420	eval-mlogloss:0.72728
[34]	train-mlogloss:0.73616	eval-mlogloss:0.71881
[35]	train-mlogloss:0.72971	eval-mlogloss:0.71220
[36]	train-mlogloss:0.72184	eval-mlogloss:0.70385
[37]	train-mlogloss:0.71438	eval-mlogloss:0.69587
[38]	train-mlogloss:0.70887	eval-mlogloss:0.69017
[39]	train-mlogloss:0.70124	eval-mlogloss:0.68184
[40]	train-mlogloss:0.69391	eval-mlogloss:0.67424
[41]	train-mlogloss:0.68672	eval-mlogloss:0.66642
[42]	train-mlogloss:0.67979	eval-mlogloss:0.65911
[43]	train-mlogloss:0.67272	eval-mlogloss:0.65125
[44]	train-mlogloss:0.66586	eval-mlogloss:0.64369
[45]	train-mlogloss:0.65875	eval-mlogloss:0.63601
[46]	train-mlogloss:0.65188	eval-mlogloss:0.62881
[47]	train-mlogloss:0.64526	eval-mlogloss:0.62185
[48]	train-mlogloss:0.63872	eval-mlogloss:0.61478
[49]	train-mlogloss:0.63224	eval-mlogloss:0.60785
[50]	train-mlogloss:0.62586	eval-mlogloss:0.60098
[51]	train-mlogloss:0.61973	eval-mlogloss:0.59432
[52]	train-mlogloss:0.61371	eval-mlogloss:0.58764
[53]	train-mlogloss:0.60774	eval-mlogloss:0.58100
[54]	train-mlogloss:0.60160	eval-mlogloss:0.57449
[55]	train-mlogloss:0.59559	eval-mlogloss:0.56786
[56]	train-mlogloss:0.58975	eval-mlogloss:0.56154
[57]	train-mlogloss:0.58448	eval-mlogloss:0.55567
[58]	train-mlogloss:0.57891	eval-mlogloss:0.54957
[59]	train-mlogloss:0.57357	eval-mlogloss:0.54396
[60]	train-mlogloss:0.56841	eval-mlogloss:0.53846
[61]	train-mlogloss:0.56321	eval-mlogloss:0.53303
[62]	train-mlogloss:0.55793	eval-mlogloss:0.52743
[63]	train-mlogloss:0.55261	eval-mlogloss:0.52172
[64]	train-mlogloss:0.54770	eval-mlogloss:0.51669
[65]	train-mlogloss:0.54266	eval-mlogloss:0.51169
[66]	train-mlogloss:0.53731	eval-mlogloss:0.50586
[67]	train-mlogloss:0.53261	eval-mlogloss:0.50082
[68]	train-mlogloss:0.52789	eval-mlogloss:0.49563
[69]	train-mlogloss:0.52305	eval-mlogloss:0.49055
[70]	train-mlogloss:0.51852	eval-mlogloss:0.48563
[71]	train-mlogloss:0.51427	eval-mlogloss:0.48124
[72]	train-mlogloss:0.51064	eval-mlogloss:0.47708
[73]	train-mlogloss:0.50604	eval-mlogloss:0.47189
[74]	train-mlogloss:0.50179	eval-mlogloss:0.46716
[75]	train-mlogloss:0.49790	eval-mlogloss:0.46327
[76]	train-mlogloss:0.49328	eval-mlogloss:0.45811
[77]	train-mlogloss:0.48927	eval-mlogloss:0.45355
[78]	train-mlogloss:0.48506	eval-mlogloss:0.44890
[79]	train-mlogloss:0.48121	eval-mlogloss:0.44454
[80]	train-mlogloss:0.47755	eval-mlogloss:0.44028
[81]	train-mlogloss:0.47426	eval-mlogloss:0.43697
[82]	train-mlogloss:0.47047	eval-mlogloss:0.43289
[83]	train-mlogloss:0.46731	eval-mlogloss:0.42943
[84]	train-mlogloss:0.46377	eval-mlogloss:0.42571
[85]	train-mlogloss:0.46032	eval-mlogloss:0.42197
[86]	train-mlogloss:0.45739	eval-mlogloss:0.41893
[87]	train-mlogloss:0.45417	eval-mlogloss:0.41573
[88]	train-mlogloss:0.45028	eval-mlogloss:0.41160
[89]	train-mlogloss:0.44727	eval-mlogloss:0.40842
[90]	train-mlogloss:0.44445	eval-mlogloss:0.40545
[91]	train-mlogloss:0.44086	eval-mlogloss:0.40147
[92]	train-mlogloss:0.43729	eval-mlogloss:0.39784
[93]	train-mlogloss:0.43392	eval-mlogloss:0.39409
[94]	train-mlogloss:0.43062	eval-mlogloss:0.39080
[95]	train-mlogloss:0.42741	eval-mlogloss:0.38723
[96]	train-mlogloss:0.42409	eval-mlogloss:0.38350
[97]	train-mlogloss:0.42098	eval-mlogloss:0.37989
[98]	train-mlogloss:0.41746	eval-mlogloss:0.37609
[99]	train-mlogloss:0.41496	eval-mlogloss:0.37326
[100]	train-mlogloss:0.41182	eval-mlogloss:0.36960
[101]	train-mlogloss:0.40917	eval-mlogloss:0.36692
[102]	train-mlogloss:0.40657	eval-mlogloss:0.36379
[103]	train-mlogloss:0.40424	eval-mlogloss:0.36140
[104]	train-mlogloss:0.40088	eval-mlogloss:0.35764
[105]	train-mlogloss:0.39849	eval-mlogloss:0.35503
[106]	train-mlogloss:0.39567	eval-mlogloss:0.35186
[107]	train-mlogloss:0.39327	eval-mlogloss:0.34919
[108]	train-mlogloss:0.39082	eval-mlogloss:0.34655
[109]	train-mlogloss:0.38792	eval-mlogloss:0.34331
[110]	train-mlogloss:0.38555	eval-mlogloss:0.34081
[111]	train-mlogloss:0.38324	eval-mlogloss:0.33824
[112]	train-mlogloss:0.38080	eval-mlogloss:0.33571
[113]	train-mlogloss:0.37870	eval-mlogloss:0.33308
[114]	train-mlogloss:0.37640	eval-mlogloss:0.33043
[115]	train-mlogloss:0.37401	eval-mlogloss:0.32765
[116]	train-mlogloss:0.37185	eval-mlogloss:0.32534
[117]	train-mlogloss:0.36891	eval-mlogloss:0.32205
[118]	train-mlogloss:0.36702	eval-mlogloss:0.32020
[119]	train-mlogloss:0.36477	eval-mlogloss:0.31775
[120]	train-mlogloss:0.36233	eval-mlogloss:0.31487
[121]	train-mlogloss:0.35962	eval-mlogloss:0.31191
[122]	train-mlogloss:0.35757	eval-mlogloss:0.30964
[123]	train-mlogloss:0.35579	eval-mlogloss:0.30777
[124]	train-mlogloss:0.35339	eval-mlogloss:0.30499
[125]	train-mlogloss:0.35143	eval-mlogloss:0.30271
[126]	train-mlogloss:0.35037	eval-mlogloss:0.30150
[127]	train-mlogloss:0.34840	eval-mlogloss:0.29938
[128]	train-mlogloss:0.34642	eval-mlogloss:0.29721
[129]	train-mlogloss:0.34550	eval-mlogloss:0.29603
[130]	train-mlogloss:0.34392	eval-mlogloss:0.29441
[131]	train-mlogloss:0.34225	eval-mlogloss:0.29244
[132]	train-mlogloss:0.34039	eval-mlogloss:0.29047
[133]	train-mlogloss:0.33859	eval-mlogloss:0.28833
[134]	train-mlogloss:0.33704	eval-mlogloss:0.28660
[135]	train-mlogloss:0.33521	eval-mlogloss:0.28451
[136]	train-mlogloss:0.33349	eval-mlogloss:0.28254
[137]	train-mlogloss:0.33185	eval-mlogloss:0.28071
[138]	train-mlogloss:0.33021	eval-mlogloss:0.27896
[139]	train-mlogloss:0.32935	eval-mlogloss:0.27793
[140]	train-mlogloss:0.32798	eval-mlogloss:0.27633
[141]	train-mlogloss:0.32629	eval-mlogloss:0.27432
[142]	train-mlogloss:0.32470	eval-mlogloss:0.27263
[143]	train-mlogloss:0.32297	eval-mlogloss:0.27081
[144]	train-mlogloss:0.32129	eval-mlogloss:0.26898
[145]	train-mlogloss:0.31950	eval-mlogloss:0.26694
[146]	train-mlogloss:0.31788	eval-mlogloss:0.26509
[147]	train-mlogloss:0.31654	eval-mlogloss:0.26341
[148]	train-mlogloss:0.31484	eval-mlogloss:0.26142
[149]	train-mlogloss:0.31324	eval-mlogloss:0.25965
[150]	train-mlogloss:0.31179	eval-mlogloss:0.25806
[151]	train-mlogloss:0.31061	eval-mlogloss:0.25683
[152]	train-mlogloss:0.31005	eval-mlogloss:0.25619
[153]	train-mlogloss:0.30845	eval-mlogloss:0.25445
[154]	train-mlogloss:0.30686	eval-mlogloss:0.25283
[155]	train-mlogloss:0.30545	eval-mlogloss:0.25142
[156]	train-mlogloss:0.30417	eval-mlogloss:0.24994
[157]	train-mlogloss:0.30382	eval-mlogloss:0.24933
[158]	train-mlogloss:0.30312	eval-mlogloss:0.24860
[159]	train-mlogloss:0.30173	eval-mlogloss:0.24713
[160]	train-mlogloss:0.30023	eval-mlogloss:0.24526
[161]	train-mlogloss:0.29945	eval-mlogloss:0.24445
[162]	train-mlogloss:0.29885	eval-mlogloss:0.24371
[163]	train-mlogloss:0.29829	eval-mlogloss:0.24302
[164]	train-mlogloss:0.29741	eval-mlogloss:0.24203
[165]	train-mlogloss:0.29673	eval-mlogloss:0.24125
[166]	train-mlogloss:0.29604	eval-mlogloss:0.24039
[167]	train-mlogloss:0.29524	eval-mlogloss:0.23938
[168]	train-mlogloss:0.29404	eval-mlogloss:0.23813
[169]	train-mlogloss:0.29342	eval-mlogloss:0.23730
[170]	train-mlogloss:0.29225	eval-mlogloss:0.23592
[171]	train-mlogloss:0.29169	eval-mlogloss:0.23524
[172]	train-mlogloss:0.29052	eval-mlogloss:0.23396
[173]	train-mlogloss:0.29000	eval-mlogloss:0.23333
[174]	train-mlogloss:0.28934	eval-mlogloss:0.23243
[175]	train-mlogloss:0.28875	eval-mlogloss:0.23180
[176]	train-mlogloss:0.28786	eval-mlogloss:0.23088
[177]	train-mlogloss:0.28661	eval-mlogloss:0.22957
[178]	train-mlogloss:0.28611	eval-mlogloss:0.22889
[179]	train-mlogloss:0.28564	eval-mlogloss:0.22836
[180]	train-mlogloss:0.28556	eval-mlogloss:0.22814
[181]	train-mlogloss:0.28553	eval-mlogloss:0.22810
[182]	train-mlogloss:0.28547	eval-mlogloss:0.22791
[183]	train-mlogloss:0.28481	eval-mlogloss:0.22706
[184]	train-mlogloss:0.28360	eval-mlogloss:0.22561
[185]	train-mlogloss:0.28359	eval-mlogloss:0.22560
[186]	train-mlogloss:0.28269	eval-mlogloss:0.22456
[187]	train-mlogloss:0.28202	eval-mlogloss:0.22387
[188]	train-mlogloss:0.28198	eval-mlogloss:0.22386
[189]	train-mlogloss:0.28194	eval-mlogloss:0.22375
[190]	train-mlogloss:0.28187	eval-mlogloss:0.22373
[191]	train-mlogloss:0.28180	eval-mlogloss:0.22353
[192]	train-mlogloss:0.28165	eval-mlogloss:0.22332
[193]	train-mlogloss:0.28138	eval-mlogloss:0.22298
[194]	train-mlogloss:0.28084	eval-mlogloss:0.22234
[195]	train-mlogloss:0.27994	eval-mlogloss:0.22146
[196]	train-mlogloss:0.27991	eval-mlogloss:0.22145
[197]	train-mlogloss:0.27924	eval-mlogloss:0.22061
[198]	train-mlogloss:0.27922	eval-mlogloss:0.22064
[199]	train-mlogloss:0.27912	eval-mlogloss:0.22065
[200]	train-mlogloss:0.27905	eval-mlogloss:0.22061
[201]	train-mlogloss:0.27788	eval-mlogloss:0.21929
[202]	train-mlogloss:0.27781	eval-mlogloss:0.21923
[203]	train-mlogloss:0.27773	eval-mlogloss:0.21901
[204]	train-mlogloss:0.27718	eval-mlogloss:0.21831
[205]	train-mlogloss:0.27712	eval-mlogloss:0.21813
[206]	train-mlogloss:0.27705	eval-mlogloss:0.21809
[207]	train-mlogloss:0.27696	eval-mlogloss:0.21799
[208]	train-mlogloss:0.27642	eval-mlogloss:0.21741
[209]	train-mlogloss:0.27517	eval-mlogloss:0.21608
[210]	train-mlogloss:0.27509	eval-mlogloss:0.21588
[211]	train-mlogloss:0.27468	eval-mlogloss:0.21534
[212]	train-mlogloss:0.27462	eval-mlogloss:0.21517
[213]	train-mlogloss:0.27455	eval-mlogloss:0.21496
[214]	train-mlogloss:0.27405	eval-mlogloss:0.21434
[215]	train-mlogloss:0.27292	eval-mlogloss:0.21318
[216]	train-mlogloss:0.27242	eval-mlogloss:0.21238
[217]	train-mlogloss:0.27239	eval-mlogloss:0.21236
[218]	train-mlogloss:0.27195	eval-mlogloss:0.21175
[219]	train-mlogloss:0.27123	eval-mlogloss:0.21110
[220]	train-mlogloss:0.27117	eval-mlogloss:0.21105
[221]	train-mlogloss:0.27075	eval-mlogloss:0.21055
[222]	train-mlogloss:0.27071	eval-mlogloss:0.21042
[223]	train-mlogloss:0.27065	eval-mlogloss:0.21028
[224]	train-mlogloss:0.27005	eval-mlogloss:0.20940
[225]	train-mlogloss:0.26952	eval-mlogloss:0.20870
[226]	train-mlogloss:0.26953	eval-mlogloss:0.20869
[227]	train-mlogloss:0.26952	eval-mlogloss:0.20868
[228]	train-mlogloss:0.26947	eval-mlogloss:0.20865
[229]	train-mlogloss:0.26904	eval-mlogloss:0.20822
[230]	train-mlogloss:0.26898	eval-mlogloss:0.20806
[231]	train-mlogloss:0.26897	eval-mlogloss:0.20805
[232]	train-mlogloss:0.26894	eval-mlogloss:0.20804
[233]	train-mlogloss:0.26893	eval-mlogloss:0.20806
[234]	train-mlogloss:0.26877	eval-mlogloss:0.20787
[235]	train-mlogloss:0.26792	eval-mlogloss:0.20697
[236]	train-mlogloss:0.26789	eval-mlogloss:0.20695
[237]	train-mlogloss:0.26787	eval-mlogloss:0.20694
[238]	train-mlogloss:0.26781	eval-mlogloss:0.20693
[239]	train-mlogloss:0.26778	eval-mlogloss:0.20690
[240]	train-mlogloss:0.26769	eval-mlogloss:0.20664
[241]	train-mlogloss:0.26728	eval-mlogloss:0.20619
[242]	train-mlogloss:0.26692	eval-mlogloss:0.20573
[243]	train-mlogloss:0.26691	eval-mlogloss:0.20572
[244]	train-mlogloss:0.26691	eval-mlogloss:0.20572
[245]	train-mlogloss:0.26688	eval-mlogloss:0.20569
[246]	train-mlogloss:0.26685	eval-mlogloss:0.20563
[247]	train-mlogloss:0.26683	eval-mlogloss:0.20563
[248]	train-mlogloss:0.26683	eval-mlogloss:0.20563
[249]	train-mlogloss:0.26646	eval-mlogloss:0.20516
[250]	train-mlogloss:0.26642	eval-mlogloss:0.20510
[251]	train-mlogloss:0.26634	eval-mlogloss:0.20487
[252]	train-mlogloss:0.26630	eval-mlogloss:0.20482
[253]	train-mlogloss:0.26627	eval-mlogloss:0.20480
[254]	train-mlogloss:0.26624	eval-mlogloss:0.20479
[255]	train-mlogloss:0.26619	eval-mlogloss:0.20475
[256]	train-mlogloss:0.26612	eval-mlogloss:0.20467
[257]	train-mlogloss:0.26609	eval-mlogloss:0.20463
[258]	train-mlogloss:0.26569	eval-mlogloss:0.20412
[259]	train-mlogloss:0.26533	eval-mlogloss:0.20363
[260]	train-mlogloss:0.26529	eval-mlogloss:0.20349
[261]	train-mlogloss:0.26470	eval-mlogloss:0.20282
[262]	train-mlogloss:0.26419	eval-mlogloss:0.20221
[263]	train-mlogloss:0.26413	eval-mlogloss:0.20216
[264]	train-mlogloss:0.26400	eval-mlogloss:0.20200
[265]	train-mlogloss:0.26387	eval-mlogloss:0.20183
[266]	train-mlogloss:0.26380	eval-mlogloss:0.20164
[267]	train-mlogloss:0.26373	eval-mlogloss:0.20157
[268]	train-mlogloss:0.26359	eval-mlogloss:0.20140
[269]	train-mlogloss:0.26356	eval-mlogloss:0.20138
[270]	train-mlogloss:0.26309	eval-mlogloss:0.20067
[271]	train-mlogloss:0.26309	eval-mlogloss:0.20067
[272]	train-mlogloss:0.26246	eval-mlogloss:0.20007
[273]	train-mlogloss:0.26244	eval-mlogloss:0.20005
[274]	train-mlogloss:0.26244	eval-mlogloss:0.20005
[275]	train-mlogloss:0.26238	eval-mlogloss:0.20003
[276]	train-mlogloss:0.26238	eval-mlogloss:0.20003
[277]	train-mlogloss:0.26234	eval-mlogloss:0.20001
[278]	train-mlogloss:0.26189	eval-mlogloss:0.19945
[279]	train-mlogloss:0.26186	eval-mlogloss:0.19942
[280]	train-mlogloss:0.26146	eval-mlogloss:0.19885
[281]	train-mlogloss:0.26142	eval-mlogloss:0.19884
[282]	train-mlogloss:0.26139	eval-mlogloss:0.19880
[283]	train-mlogloss:0.26120	eval-mlogloss:0.19853
[284]	train-mlogloss:0.26119	eval-mlogloss:0.19849
[285]	train-mlogloss:0.26119	eval-mlogloss:0.19850
[286]	train-mlogloss:0.26082	eval-mlogloss:0.19802
[287]	train-mlogloss:0.26036	eval-mlogloss:0.19748
[288]	train-mlogloss:0.26032	eval-mlogloss:0.19743
[289]	train-mlogloss:0.25984	eval-mlogloss:0.19691
[290]	train-mlogloss:0.25981	eval-mlogloss:0.19690
[291]	train-mlogloss:0.25980	eval-mlogloss:0.19690
[292]	train-mlogloss:0.25978	eval-mlogloss:0.19689
[293]	train-mlogloss:0.25940	eval-mlogloss:0.19641
[294]	train-mlogloss:0.25935	eval-mlogloss:0.19640
[295]	train-mlogloss:0.25930	eval-mlogloss:0.19621
[296]	train-mlogloss:0.25930	eval-mlogloss:0.19623
[297]	train-mlogloss:0.25921	eval-mlogloss:0.19598
[298]	train-mlogloss:0.25916	eval-mlogloss:0.19592
[299]	train-mlogloss:0.25915	eval-mlogloss:0.19589

[I 2026-03-04 10:34:50,338] Trial 24 finished with value: 1.0 and parameters: {'lambda': 0.01581250246060432, 'alpha': 0.08746503545779447, 'eta': 0.010793890880213236, 'gamma': 0.05251898588845779, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.6048523258960831, 'colsample_bytree': 0.8637164324966988}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00817	eval-mlogloss:1.01061
[1]	train-mlogloss:0.89518	eval-mlogloss:0.89247

[I 2026-03-04 10:34:50,383] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04767	eval-mlogloss:1.04323
[1]	train-mlogloss:0.96589	eval-mlogloss:0.95755

[I 2026-03-04 10:34:50,419] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.80664	eval-mlogloss:0.78288
[1]	train-mlogloss:0.61763	eval-mlogloss:0.58550

[I 2026-03-04 10:34:50,476] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98405	eval-mlogloss:0.97385
[1]	train-mlogloss:0.83329	eval-mlogloss:0.81158

[I 2026-03-04 10:34:50,517] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91553	eval-mlogloss:0.90695
[1]	train-mlogloss:0.72049	eval-mlogloss:0.69784

[I 2026-03-04 10:34:50,616] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97369	eval-mlogloss:0.97873
[1]	train-mlogloss:0.84266	eval-mlogloss:0.84453

[I 2026-03-04 10:34:50,706] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07934	eval-mlogloss:1.08318
[1]	train-mlogloss:1.03524	eval-mlogloss:1.03702
[2]	train-mlogloss:0.99309	eval-mlogloss:0.99203
[3]	train-mlogloss:0.96283	eval-mlogloss:0.95859
[4]	train-mlogloss:0.93114	eval-mlogloss:0.92575
[5]	train-mlogloss:0.89508	eval-mlogloss:0.88736
[6]	train-mlogloss:0.86886	eval-mlogloss:0.86129
[7]	train-mlogloss:0.84908	eval-mlogloss:0.84263

[I 2026-03-04 10:34:51,240] Trial 31 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06946	eval-mlogloss:1.07262
[1]	train-mlogloss:1.03015	eval-mlogloss:1.03155
[2]	train-mlogloss:0.99277	eval-mlogloss:0.99206
[3]	train-mlogloss:0.95754	eval-mlogloss:0.95549
[4]	train-mlogloss:0.92380	eval-mlogloss:0.92001
[5]	train-mlogloss:0.89138	eval-mlogloss:0.88553
[6]	train-mlogloss:0.86079	eval-mlogloss:0.85401
[7]	train-mlogloss:0.83248	eval-mlogloss:0.82497

[I 2026-03-04 10:34:51,381] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06141	eval-mlogloss:1.06538
[1]	train-mlogloss:0.97871	eval-mlogloss:0.97895
[2]	train-mlogloss:0.90486	eval-mlogloss:0.90278
[3]	train-mlogloss:0.85472	eval-mlogloss:0.84682
[4]	train-mlogloss:0.80411	eval-mlogloss:0.79241
[5]	train-mlogloss:0.74759	eval-mlogloss:0.73202
[6]	train-mlogloss:0.70849	eval-mlogloss:0.69426
[7]	train-mlogloss:0.68007	eval-mlogloss:0.66622

[I 2026-03-04 10:34:51,473] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.09288	eval-mlogloss:1.09495
[1]	train-mlogloss:1.07910	eval-mlogloss:1.08060
[2]	train-mlogloss:1.06552	eval-mlogloss:1.06641
[3]	train-mlogloss:1.05513	eval-mlogloss:1.05498
[4]	train-mlogloss:1.04431	eval-mlogloss:1.04341
[5]	train-mlogloss:1.03109	eval-mlogloss:1.02949
[6]	train-mlogloss:1.02128	eval-mlogloss:1.01968
[7]	train-mlogloss:1.01394	eval-mlogloss:1.01271
[8]	train-mlogloss:1.00160	eval-mlogloss:0.99962
[9]	train-mlogloss:0.99215	eval-mlogloss:0.99002
[10]	train-mlogloss:0.98021	eval-mlogloss:0.97760
[11]	train-mlogloss:0.96947	eval-mlogloss:0.96667
[12]	train-mlogloss:0.96514	eval-mlogloss:0.96152
[13]	train-mlogloss:0.95372	eval-mlogloss:0.94921
[14]	train-mlogloss:0.94986	eval-mlogloss:0.94595
[15]	train-mlogloss:0.94315	eval-mlogloss:0.93949
[16]	train-mlogloss:0.93587	eval-mlogloss:0.93182
[17]	train-mlogloss:0.92719	eval-mlogloss:0.92348
[18]	train-mlogloss:0.92075	eval-mlogloss:0.91733
[19]	train-mlogloss:0.91459	eval-mlogloss:0.91162
[20]	train-mlogloss:0.90404	eval-mlogloss:0.90049
[21]	train-mlogloss:0.89656	eval-mlogloss:0.89282
[22]	train-mlogloss:0.88993	eval-mlogloss:0.88589
[23]	train-mlogloss:0.87968	eval-mlogloss:0.87508
[24]	train-mlogloss:0.87366	eval-mlogloss:0.86871
[25]	train-mlogloss:0.86615	eval-mlogloss:0.86044
[26]	train-mlogloss:0.85811	eval-mlogloss:0.85237
[27]	train-mlogloss:0.85568	eval-mlogloss:0.85041
[28]	train-mlogloss:0.85223	eval-mlogloss:0.84740
[29]	train-mlogloss:0.84460	eval-mlogloss:0.83917
[30]	train-mlogloss:0.83744	eval-mlogloss:0.83197
[31]	train-mlogloss:0.83493	eval-mlogloss:0.83008
[32]	train-mlogloss:0.82996	eval-mlogloss:0.82549
[33]	train-mlogloss:0.82565	eval-mlogloss:0.82079
[34]	train-mlogloss:0.81775	eval-mlogloss:0.81244
[35]	train-mlogloss:0.81301	eval-mlogloss:0.80736
[36]	train-mlogloss:0.80900	eval-mlogloss:0.80364
[37]	train-mlogloss:0.80265	eval-mlogloss:0.79749
[38]	train-mlogloss:0.79590	eval-mlogloss:0.79053
[39]	train-mlogloss:0.79045	eval-mlogloss:0.78525
[40]	train-mlogloss:0.78748	eval-mlogloss:0.78269
[41]	train-mlogloss:0.78124	eval-mlogloss:0.77564
[42]	train-mlogloss:0.77901	eval-mlogloss:0.77381
[43]	train-mlogloss:0.77299	eval-mlogloss:0.76758
[44]	train-mlogloss:0.76668	eval-mlogloss:0.76065
[45]	train-mlogloss:0.76303	eval-mlogloss:0.75668
[46]	train-mlogloss:0.75677	eval-mlogloss:0.75011
[47]	train-mlogloss:0.75225	eval-mlogloss:0.74558
[48]	train-mlogloss:0.74564	eval-mlogloss:0.73868
[49]	train-mlogloss:0.73916	eval-mlogloss:0.73208
[50]	train-mlogloss:0.73303	eval-mlogloss:0.72538
[51]	train-mlogloss:0.72925	eval-mlogloss:0.72175
[52]	train-mlogloss:0.72559	eval-mlogloss:0.71821
[53]	train-mlogloss:0.71803	eval-mlogloss:0.70982
[54]	train-mlogloss:0.71426	eval-mlogloss:0.70615
[55]	train-mlogloss:0.70676	eval-mlogloss:0.69849
[56]	train-mlogloss:0.70100	eval-mlogloss:0.69273
[57]	train-mlogloss:0.69396	eval-mlogloss:0.68511
[58]	train-mlogloss:0.69004	eval-mlogloss:0.68131
[59]	train-mlogloss:0.68766	eval-mlogloss:0.67889
[60]	train-mlogloss:0.68268	eval-mlogloss:0.67339
[61]	train-mlogloss:0.67827	eval-mlogloss:0.66884
[62]	train-mlogloss:0.67129	eval-mlogloss:0.66162
[63]	train-mlogloss:0.66767	eval-mlogloss:0.65779
[64]	train-mlogloss:0.66531	eval-mlogloss:0.65540
[65]	train-mlogloss:0.66142	eval-mlogloss:0.65145
[66]	train-mlogloss:0.65610	eval-mlogloss:0.64584
[67]	train-mlogloss:0.65181	eval-mlogloss:0.64161
[68]	train-mlogloss:0.64977	eval-mlogloss:0.63936
[69]	train-mlogloss:0.64341	eval-mlogloss:0.63267
[70]	train-mlogloss:0.63943	eval-mlogloss:0.62845
[71]	train-mlogloss:0.63290	eval-mlogloss:0.62139
[72]	train-mlogloss:0.62798	eval-mlogloss:0.61637
[73]	train-mlogloss:0.62419	eval-mlogloss:0.61238
[74]	train-mlogloss:0.61984	eval-mlogloss:0.60779
[75]	train-mlogloss:0.61456	eval-mlogloss:0.60222
[76]	train-mlogloss:0.61142	eval-mlogloss:0.59930
[77]	train-mlogloss:0.60874	eval-mlogloss:0.59694
[78]	train-mlogloss:0.60568	eval-mlogloss:0.59391
[79]	train-mlogloss:0.60304	eval-mlogloss:0.59177
[80]	train-mlogloss:0.60035	eval-mlogloss:0.58884
[81]	train-mlogloss:0.59588	eval-mlogloss:0.58428
[82]	train-mlogloss:0.59305	eval-mlogloss:0.58139
[83]	train-mlogloss:0.58918	eval-mlogloss:0.57721
[84]	train-mlogloss:0.58584	eval-mlogloss:0.57364
[85]	train-mlogloss:0.58160	eval-mlogloss:0.56909
[86]	train-mlogloss:0.57718	eval-mlogloss:0.56426
[87]	train-mlogloss:0.57274	eval-mlogloss:0.55971
[88]	train-mlogloss:0.56923	eval-mlogloss:0.55549
[89]	train-mlogloss:0.56470	eval-mlogloss:0.55073
[90]	train-mlogloss:0.56071	eval-mlogloss:0.54628
[91]	train-mlogloss:0.55759	eval-mlogloss:0.54309
[92]	train-mlogloss:0.55301	eval-mlogloss:0.53824
[93]	train-mlogloss:0.55135	eval-mlogloss:0.53683
[94]	train-mlogloss:0.54618	eval-mlogloss:0.53101
[95]	train-mlogloss:0.54171	eval-mlogloss:0.52589
[96]	train-mlogloss:0.53681	eval-mlogloss:0.52063
[97]	train-mlogloss:0.53414	eval-mlogloss:0.51795
[98]	train-mlogloss:0.53112	eval-mlogloss:0.51461
[99]	train-mlogloss:0.53000	eval-mlogloss:0.51376
[100]	train-mlogloss:0.52659	eval-mlogloss:0.51029
[101]	train-mlogloss:0.52358	eval-mlogloss:0.50683
[102]	train-mlogloss:0.52129	eval-mlogloss:0.50462
[103]	train-mlogloss:0.51653	eval-mlogloss:0.49949
[104]	train-mlogloss:0.51379	eval-mlogloss:0.49676
[105]	train-mlogloss:0.51133	eval-mlogloss:0.49421
[106]	train-mlogloss:0.50818	eval-mlogloss:0.49094
[107]	train-mlogloss:0.50346	eval-mlogloss:0.48560
[108]	train-mlogloss:0.50099	eval-mlogloss:0.48285
[109]	train-mlogloss:0.49644	eval-mlogloss:0.47771
[110]	train-mlogloss:0.49374	eval-mlogloss:0.47452
[111]	train-mlogloss:0.49028	eval-mlogloss:0.47066
[112]	train-mlogloss:0.48776	eval-mlogloss:0.46817
[113]	train-mlogloss:0.48327	eval-mlogloss:0.46311
[114]	train-mlogloss:0.48096	eval-mlogloss:0.46077
[115]	train-mlogloss:0.47808	eval-mlogloss:0.45771
[116]	train-mlogloss:0.47386	eval-mlogloss:0.45311
[117]	train-mlogloss:0.47050	eval-mlogloss:0.44947
[118]	train-mlogloss:0.46757	eval-mlogloss:0.44622
[119]	train-mlogloss:0.46531	eval-mlogloss:0.44379
[120]	train-mlogloss:0.46132	eval-mlogloss:0.43923
[121]	train-mlogloss:0.45792	eval-mlogloss:0.43557
[122]	train-mlogloss:0.45388	eval-mlogloss:0.43094
[123]	train-mlogloss:0.45046	eval-mlogloss:0.42709
[124]	train-mlogloss:0.44764	eval-mlogloss:0.42407
[125]	train-mlogloss:0.44483	eval-mlogloss:0.42085
[126]	train-mlogloss:0.44282	eval-mlogloss:0.41880
[127]	train-mlogloss:0.44083	eval-mlogloss:0.41661
[128]	train-mlogloss:0.43802	eval-mlogloss:0.41356
[129]	train-mlogloss:0.43617	eval-mlogloss:0.41156
[130]	train-mlogloss:0.43537	eval-mlogloss:0.41111
[131]	train-mlogloss:0.43168	eval-mlogloss:0.40687
[132]	train-mlogloss:0.42873	eval-mlogloss:0.40369
[133]	train-mlogloss:0.42620	eval-mlogloss:0.40098
[134]	train-mlogloss:0.42466	eval-mlogloss:0.39956
[135]	train-mlogloss:0.42188	eval-mlogloss:0.39630
[136]	train-mlogloss:0.41957	eval-mlogloss:0.39367
[137]	train-mlogloss:0.41607	eval-mlogloss:0.38979
[138]	train-mlogloss:0.41355	eval-mlogloss:0.38718
[139]	train-mlogloss:0.41196	eval-mlogloss:0.38581
[140]	train-mlogloss:0.40923	eval-mlogloss:0.38280
[141]	train-mlogloss:0.40689	eval-mlogloss:0.38023
[142]	train-mlogloss:0.40422	eval-mlogloss:0.37739
[143]	train-mlogloss:0.40078	eval-mlogloss:0.37367
[144]	train-mlogloss:0.39810	eval-mlogloss:0.37071
[145]	train-mlogloss:0.39580	eval-mlogloss:0.36816
[146]	train-mlogloss:0.39340	eval-mlogloss:0.36544
[147]	train-mlogloss:0.39117	eval-mlogloss:0.36302
[148]	train-mlogloss:0.38870	eval-mlogloss:0.36020
[149]	train-mlogloss:0.38782	eval-mlogloss:0.35922
[150]	train-mlogloss:0.38475	eval-mlogloss:0.35588
[151]	train-mlogloss:0.38172	eval-mlogloss:0.35244
[152]	train-mlogloss:0.38023	eval-mlogloss:0.35085
[153]	train-mlogloss:0.37813	eval-mlogloss:0.34873
[154]	train-mlogloss:0.37503	eval-mlogloss:0.34547
[155]	train-mlogloss:0.37281	eval-mlogloss:0.34293
[156]	train-mlogloss:0.37047	eval-mlogloss:0.34030
[157]	train-mlogloss:0.36899	eval-mlogloss:0.33867
[158]	train-mlogloss:0.36627	eval-mlogloss:0.33563
[159]	train-mlogloss:0.36484	eval-mlogloss:0.33403
[160]	train-mlogloss:0.36245	eval-mlogloss:0.33142
[161]	train-mlogloss:0.35969	eval-mlogloss:0.32847
[162]	train-mlogloss:0.35825	eval-mlogloss:0.32686
[163]	train-mlogloss:0.35702	eval-mlogloss:0.32529
[164]	train-mlogloss:0.35629	eval-mlogloss:0.32456
[165]	train-mlogloss:0.35500	eval-mlogloss:0.32297
[166]	train-mlogloss:0.35235	eval-mlogloss:0.32008
[167]	train-mlogloss:0.34976	eval-mlogloss:0.31711
[168]	train-mlogloss:0.34783	eval-mlogloss:0.31491
[169]	train-mlogloss:0.34673	eval-mlogloss:0.31380
[170]	train-mlogloss:0.34628	eval-mlogloss:0.31349
[171]	train-mlogloss:0.34464	eval-mlogloss:0.31182
[172]	train-mlogloss:0.34405	eval-mlogloss:0.31118
[173]	train-mlogloss:0.34316	eval-mlogloss:0.31023
[174]	train-mlogloss:0.34180	eval-mlogloss:0.30857
[175]	train-mlogloss:0.34051	eval-mlogloss:0.30732
[176]	train-mlogloss:0.33835	eval-mlogloss:0.30500
[177]	train-mlogloss:0.33751	eval-mlogloss:0.30416
[178]	train-mlogloss:0.33570	eval-mlogloss:0.30222
[179]	train-mlogloss:0.33489	eval-mlogloss:0.30123
[180]	train-mlogloss:0.33293	eval-mlogloss:0.29902
[181]	train-mlogloss:0.33098	eval-mlogloss:0.29692
[182]	train-mlogloss:0.32972	eval-mlogloss:0.29553
[183]	train-mlogloss:0.32909	eval-mlogloss:0.29507
[184]	train-mlogloss:0.32735	eval-mlogloss:0.29319
[185]	train-mlogloss:0.32572	eval-mlogloss:0.29134
[186]	train-mlogloss:0.32398	eval-mlogloss:0.28947
[187]	train-mlogloss:0.32233	eval-mlogloss:0.28759
[188]	train-mlogloss:0.32057	eval-mlogloss:0.28551
[189]	train-mlogloss:0.31824	eval-mlogloss:0.28303
[190]	train-mlogloss:0.31724	eval-mlogloss:0.28185
[191]	train-mlogloss:0.31574	eval-mlogloss:0.28008
[192]	train-mlogloss:0.31447	eval-mlogloss:0.27872
[193]	train-mlogloss:0.31320	eval-mlogloss:0.27719
[194]	train-mlogloss:0.31167	eval-mlogloss:0.27558
[195]	train-mlogloss:0.30967	eval-mlogloss:0.27344
[196]	train-mlogloss:0.30825	eval-mlogloss:0.27210
[197]	train-mlogloss:0.30613	eval-mlogloss:0.26949
[198]	train-mlogloss:0.30519	eval-mlogloss:0.26843
[199]	train-mlogloss:0.30417	eval-mlogloss:0.26729
[200]	train-mlogloss:0.30284	eval-mlogloss:0.26587
[201]	train-mlogloss:0.30190	eval-mlogloss:0.26490
[202]	train-mlogloss:0.30106	eval-mlogloss:0.26402
[203]	train-mlogloss:0.29960	eval-mlogloss:0.26250
[204]	train-mlogloss:0.29862	eval-mlogloss:0.26153
[205]	train-mlogloss:0.29786	eval-mlogloss:0.26065
[206]	train-mlogloss:0.29671	eval-mlogloss:0.25945
[207]	train-mlogloss:0.29562	eval-mlogloss:0.25816
[208]	train-mlogloss:0.29425	eval-mlogloss:0.25669
[209]	train-mlogloss:0.29252	eval-mlogloss:0.25462
[210]	train-mlogloss:0.29207	eval-mlogloss:0.25413
[211]	train-mlogloss:0.29129	eval-mlogloss:0.25348
[212]	train-mlogloss:0.28996	eval-mlogloss:0.25204
[213]	train-mlogloss:0.28833	eval-mlogloss:0.25027
[214]	train-mlogloss:0.28668	eval-mlogloss:0.24834
[215]	train-mlogloss:0.28496	eval-mlogloss:0.24620
[216]	train-mlogloss:0.28413	eval-mlogloss:0.24528
[217]	train-mlogloss:0.28244	eval-mlogloss:0.24315
[218]	train-mlogloss:0.28194	eval-mlogloss:0.24275
[219]	train-mlogloss:0.28024	eval-mlogloss:0.24088
[220]	train-mlogloss:0.27936	eval-mlogloss:0.23997
[221]	train-mlogloss:0.27857	eval-mlogloss:0.23915
[222]	train-mlogloss:0.27782	eval-mlogloss:0.23842
[223]	train-mlogloss:0.27694	eval-mlogloss:0.23751
[224]	train-mlogloss:0.27566	eval-mlogloss:0.23626
[225]	train-mlogloss:0.27519	eval-mlogloss:0.23575
[226]	train-mlogloss:0.27416	eval-mlogloss:0.23455
[227]	train-mlogloss:0.27364	eval-mlogloss:0.23412
[228]	train-mlogloss:0.27274	eval-mlogloss:0.23330
[229]	train-mlogloss:0.27182	eval-mlogloss:0.23226
[230]	train-mlogloss:0.27154	eval-mlogloss:0.23191
[231]	train-mlogloss:0.27049	eval-mlogloss:0.23066
[232]	train-mlogloss:0.27026	eval-mlogloss:0.23057
[233]	train-mlogloss:0.26929	eval-mlogloss:0.22944
[234]	train-mlogloss:0.26778	eval-mlogloss:0.22758
[235]	train-mlogloss:0.26658	eval-mlogloss:0.22608
[236]	train-mlogloss:0.26583	eval-mlogloss:0.22516
[237]	train-mlogloss:0.26480	eval-mlogloss:0.22403
[238]	train-mlogloss:0.26381	eval-mlogloss:0.22286
[239]	train-mlogloss:0.26298	eval-mlogloss:0.22198
[240]	train-mlogloss:0.26149	eval-mlogloss:0.22017
[241]	train-mlogloss:0.26086	eval-mlogloss:0.21956
[242]	train-mlogloss:0.25987	eval-mlogloss:0.21849
[243]	train-mlogloss:0.25922	eval-mlogloss:0.21776
[244]	train-mlogloss:0.25859	eval-mlogloss:0.21721
[245]	train-mlogloss:0.25741	eval-mlogloss:0.21585
[246]	train-mlogloss:0.25693	eval-mlogloss:0.21529
[247]	train-mlogloss:0.25670	eval-mlogloss:0.21501
[248]	train-mlogloss:0.25647	eval-mlogloss:0.21493
[249]	train-mlogloss:0.25525	eval-mlogloss:0.21333
[250]	train-mlogloss:0.25411	eval-mlogloss:0.21197
[251]	train-mlogloss:0.25335	eval-mlogloss:0.21120
[252]	train-mlogloss:0.25270	eval-mlogloss:0.21043
[253]	train-mlogloss:0.25210	eval-mlogloss:0.20970
[254]	train-mlogloss:0.25121	eval-mlogloss:0.20866
[255]	train-mlogloss:0.25075	eval-mlogloss:0.20821
[256]	train-mlogloss:0.24991	eval-mlogloss:0.20711
[257]	train-mlogloss:0.24900	eval-mlogloss:0.20604
[258]	train-mlogloss:0.24820	eval-mlogloss:0.20507
[259]	train-mlogloss:0.24797	eval-mlogloss:0.20491
[260]	train-mlogloss:0.24762	eval-mlogloss:0.20457
[261]	train-mlogloss:0.24667	eval-mlogloss:0.20348
[262]	train-mlogloss:0.24572	eval-mlogloss:0.20248
[263]	train-mlogloss:0.24476	eval-mlogloss:0.20146
[264]	train-mlogloss:0.24454	eval-mlogloss:0.20138
[265]	train-mlogloss:0.24399	eval-mlogloss:0.20077
[266]	train-mlogloss:0.24310	eval-mlogloss:0.19966
[267]	train-mlogloss:0.24243	eval-mlogloss:0.19891
[268]	train-mlogloss:0.24178	eval-mlogloss:0.19812
[269]	train-mlogloss:0.24081	eval-mlogloss:0.19683
[270]	train-mlogloss:0.23985	eval-mlogloss:0.19578
[271]	train-mlogloss:0.23926	eval-mlogloss:0.19518
[272]	train-mlogloss:0.23794	eval-mlogloss:0.19362
[273]	train-mlogloss:0.23736	eval-mlogloss:0.19302
[274]	train-mlogloss:0.23678	eval-mlogloss:0.19233
[275]	train-mlogloss:0.23554	eval-mlogloss:0.19086
[276]	train-mlogloss:0.23505	eval-mlogloss:0.19023
[277]	train-mlogloss:0.23421	eval-mlogloss:0.18927
[278]	train-mlogloss:0.23345	eval-mlogloss:0.18833
[279]	train-mlogloss:0.23266	eval-mlogloss:0.18744
[280]	train-mlogloss:0.23209	eval-mlogloss:0.18678
[281]	train-mlogloss:0.23123	eval-mlogloss:0.18582
[282]	train-mlogloss:0.23040	eval-mlogloss:0.18490
[283]	train-mlogloss:0.23019	eval-mlogloss:0.18466
[284]	train-mlogloss:0.22919	eval-mlogloss:0.18347
[285]	train-mlogloss:0.22878	eval-mlogloss:0.18306
[286]	train-mlogloss:0.22772	eval-mlogloss:0.18192
[287]	train-mlogloss:0.22681	eval-mlogloss:0.18084
[288]	train-mlogloss:0.22634	eval-mlogloss:0.18029
[289]	train-mlogloss:0.22561	eval-mlogloss:0.17949
[290]	train-mlogloss:0.22493	eval-mlogloss:0.17875
[291]	train-mlogloss:0.22408	eval-mlogloss:0.17787
[292]	train-mlogloss:0.22383	eval-mlogloss:0.17770
[293]	train-mlogloss:0.22342	eval-mlogloss:0.17734
[294]	train-mlogloss:0.22281	eval-mlogloss:0.17662
[295]	train-mlogloss:0.22223	eval-mlogloss:0.17599
[296]	train-mlogloss:0.22169	eval-mlogloss:0.17537
[297]	train-mlogloss:0.22108	eval-mlogloss:0.17468
[298]	train-mlogloss:0.22073	eval-mlogloss:0.17421
[299]	train-mlogloss:0.21982	eval-mlogloss:0.17303

[I 2026-03-04 10:34:55,038] Trial 34 finished with value: 1.0 and parameters: {'lambda': 0.00016402197050772625, 'alpha': 0.2888233097045736, 'eta': 0.010809437287339366, 'gamma': 0.015157488571930985, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7660348677356036, 'colsample_bytree': 0.44094256813480426}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.02886	eval-mlogloss:1.02551
[1]	train-mlogloss:0.96560	eval-mlogloss:0.96337

[I 2026-03-04 10:34:55,313] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08342	eval-mlogloss:1.08443
[1]	train-mlogloss:1.04451	eval-mlogloss:1.04363
[2]	train-mlogloss:1.00781	eval-mlogloss:1.00506
[3]	train-mlogloss:0.98099	eval-mlogloss:0.97483
[4]	train-mlogloss:0.95297	eval-mlogloss:0.94429
[5]	train-mlogloss:0.91989	eval-mlogloss:0.90889
[6]	train-mlogloss:0.89613	eval-mlogloss:0.88529
[7]	train-mlogloss:0.87828	eval-mlogloss:0.86790

[I 2026-03-04 10:34:55,561] Trial 36 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01910	eval-mlogloss:1.02468
[1]	train-mlogloss:0.92864	eval-mlogloss:0.92388

[I 2026-03-04 10:34:55,696] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90463	eval-mlogloss:0.89112
[1]	train-mlogloss:0.75624	eval-mlogloss:0.73386

[I 2026-03-04 10:34:56,223] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96794	eval-mlogloss:0.97224
[1]	train-mlogloss:0.81997	eval-mlogloss:0.81597

[I 2026-03-04 10:34:56,356] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00267	eval-mlogloss:1.01168
[1]	train-mlogloss:0.80828	eval-mlogloss:0.80535

[I 2026-03-04 10:34:57,413] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08289	eval-mlogloss:1.08566
[1]	train-mlogloss:1.05080	eval-mlogloss:1.05216
[2]	train-mlogloss:1.01889	eval-mlogloss:1.01760
[3]	train-mlogloss:0.99559	eval-mlogloss:0.99293
[4]	train-mlogloss:0.97171	eval-mlogloss:0.96967
[5]	train-mlogloss:0.94270	eval-mlogloss:0.93912
[6]	train-mlogloss:0.92210	eval-mlogloss:0.91709
[7]	train-mlogloss:0.90746	eval-mlogloss:0.90389

[I 2026-03-04 10:34:57,576] Trial 41 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08700	eval-mlogloss:1.09002
[1]	train-mlogloss:1.06142	eval-mlogloss:1.06282
[2]	train-mlogloss:1.03634	eval-mlogloss:1.03564
[3]	train-mlogloss:1.01771	eval-mlogloss:1.01506
[4]	train-mlogloss:0.99844	eval-mlogloss:0.99570
[5]	train-mlogloss:0.97501	eval-mlogloss:0.97109
[6]	train-mlogloss:0.95799	eval-mlogloss:0.95314
[7]	train-mlogloss:0.94596	eval-mlogloss:0.94334
[8]	train-mlogloss:0.92421	eval-mlogloss:0.91981
[9]	train-mlogloss:0.90751	eval-mlogloss:0.90281
[10]	train-mlogloss:0.88838	eval-mlogloss:0.88309
[11]	train-mlogloss:0.87132	eval-mlogloss:0.86528
[12]	train-mlogloss:0.86356	eval-mlogloss:0.85726
[13]	train-mlogloss:0.84491	eval-mlogloss:0.83694
[14]	train-mlogloss:0.83869	eval-mlogloss:0.83177
[15]	train-mlogloss:0.82743	eval-mlogloss:0.82063
[16]	train-mlogloss:0.81551	eval-mlogloss:0.80836
[17]	train-mlogloss:0.80198	eval-mlogloss:0.79580
[18]	train-mlogloss:0.79237	eval-mlogloss:0.78626
[19]	train-mlogloss:0.78304	eval-mlogloss:0.77697
[20]	train-mlogloss:0.76696	eval-mlogloss:0.76047
[21]	train-mlogloss:0.75542	eval-mlogloss:0.74744
[22]	train-mlogloss:0.74562	eval-mlogloss:0.73680
[23]	train-mlogloss:0.72987	eval-mlogloss:0.71986
[24]	train-mlogloss:0.72121	eval-mlogloss:0.71009
[25]	train-mlogloss:0.71069	eval-mlogloss:0.69863
[26]	train-mlogloss:0.69909	eval-mlogloss:0.68656
[27]	train-mlogloss:0.69548	eval-mlogloss:0.68403
[28]	train-mlogloss:0.69060	eval-mlogloss:0.68078
[29]	train-mlogloss:0.67936	eval-mlogloss:0.66832
[30]	train-mlogloss:0.66966	eval-mlogloss:0.65865
[31]	train-mlogloss:0.66586	eval-mlogloss:0.65582

[I 2026-03-04 10:34:58,227] Trial 42 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.07480	eval-mlogloss:1.07871
[1]	train-mlogloss:1.02224	eval-mlogloss:1.02231

[I 2026-03-04 10:34:58,499] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03564	eval-mlogloss:1.04741
[1]	train-mlogloss:0.96050	eval-mlogloss:0.97129

[I 2026-03-04 10:34:58,595] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08151	eval-mlogloss:1.08299
[1]	train-mlogloss:1.06003	eval-mlogloss:1.05936
[2]	train-mlogloss:1.03594	eval-mlogloss:1.03369
[3]	train-mlogloss:1.01181	eval-mlogloss:1.00901
[4]	train-mlogloss:0.98950	eval-mlogloss:0.98634
[5]	train-mlogloss:0.96685	eval-mlogloss:0.96260
[6]	train-mlogloss:0.94587	eval-mlogloss:0.94075
[7]	train-mlogloss:0.92817	eval-mlogloss:0.92430

[I 2026-03-04 10:34:58,735] Trial 45 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.94845	eval-mlogloss:0.93066
[1]	train-mlogloss:0.76005	eval-mlogloss:0.72889

[I 2026-03-04 10:34:59,150] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02843	eval-mlogloss:1.03157
[1]	train-mlogloss:0.94664	eval-mlogloss:0.94332

[I 2026-03-04 10:34:59,200] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04907	eval-mlogloss:1.04748
[1]	train-mlogloss:1.01612	eval-mlogloss:1.01014

[I 2026-03-04 10:34:59,584] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87778	eval-mlogloss:0.87761
[1]	train-mlogloss:0.67495	eval-mlogloss:0.66839

[I 2026-03-04 10:34:59,914] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 0.0012164703947697255, 'alpha': 0.13314893991574867, 'eta': 0.04235012961350021, 'gamma': 0.0017143784740760264, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.4152043367772039, 'colsample_bytree': 0.5327628311945874}
Best accuracy: 1.0

In [41]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.7.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.7.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 3.4 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.7.0

In [43]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()